### ISSUE TITLE
"Keine Kontakte vorhanden" message displayed even though contacts exist

### ISSUE THREAD

**Issue by mbiebl** [owncloud/contacts#192] opened 2016-03-11 13:58 UTC
Version: 9.0

I made a fresh installation of owncloud 9 and created a test user.
Yet the contacts app still shows "Keine Kontakte vorhanden" next to the newly created user.
Screenshot attached

![contacts](https://cloud.githubusercontent.com/assets/3609611/13703978/b093cb8c-e799-11e5-87be-fcbf1121d690.png)

**Comment by Henni** [comment] 2016-03-11 14:06
@mbiebl  Clicking the contact should replace the "Keine Kontakte vorhanden" message with the contact details, right?

**Comment by mbiebl** [comment] 2016-03-11 14:19
@Henni It does, yes

**Comment by Henni** [comment] 2016-03-11 14:21
This may get fixed with https://github.com/owncloud/contacts/pull/129

**Comment by DeepDiver1975** [comment] 2016-03-13 18:41
@mbiebl can you test #129 please to see if this fixes your observation - THX

**Comment by joergmschulz** [comment] 2016-03-14 20:02
the retrieval of a longer contact list on a slowish machine takes a long time; first, only the 'Keine Kontakte vorhanden' message pops up and no contact can be seen; after > 30 seconds the list appears but the message doesn't disappear.
And, images of large file size will no longer be displayed (adding this in the hope it has the same root cause)

**Comment by DeepDiver1975** [comment] 2016-03-15 11:28
> the retrieval of a longer contact list on a slowish machine takes a long time

tracked in #197

**Comment by DeepDiver1975** [comment] 2016-03-15 11:29
> And, images of large file size will no longer be displayed (adding this in the hope it has the same root cause)

Can I ask you to provide a example vcard for testing? THX

**Comment by joergmschulz** [comment] 2016-03-15 21:02
Yes, this is the example (anonymized, except large image, renamed to .txt)

[First Name.vcf.txt](https://github.com/owncloud/contacts/files/174811/First.Name.vcf.txt)

**Comment by DeepDiver1975** [comment] 2016-03-16 10:43
> Yes, this is the example (anonymized, except large image, renamed to .txt)

Works on latest master ... we will soon publish a new version to the appstore

![bildschirmfoto von 2016-03-16 11-43-11](https://cloud.githubusercontent.com/assets/1005065/13809709/4fb6c540-eb6c-11e5-9b31-0343678167ba.png)

**Comment by irgendwie** [comment] 2016-03-20 18:10
Fixed by #233.

**Closed as completed by irgendwie** 2016-03-20 18:10 UTC
Labels: bug
