### ISSUE TITLE
OC9 - no contacts found message shown until an address record has been selected

### ISSUE THREAD

**Issue by j-ed** [owncloud/contacts#251] opened 2016-03-21 08:22 UTC
## Expected behavior

When opening the contacts app a message like 'loading contacts' etc. should be
shown until all address data have been loaded instead of `no contacts found`.
## Current behavior

When opening the contacts app the higly irritating `no contacts found` message is
shown as long as no contact has been selected, although address data has already 
been loaded.

![2016-03-21 09_19_35-kontakte - owncloud](https://cloud.githubusercontent.com/assets/2572764/13913376/48a47fee-ef46-11e5-858a-242002b24ab1.jpg)
#### Server Configuration

OS: Linux 3.2.75
Web server: Apache2 2.4.18
Database: MariaDB 5.5.46
PHP version: 5.6.17
ownCloud version: 9.0.0
Contacts app version: 1.0.0
Updated from OC8.2.2
#### Client Configuration

Browser: Firefox 45.0.1
Operating system: Windows 7

**Comment by aspdye** [comment] 2016-03-21 08:56
Duplicate of #24 :wink:

**Closed as completed** 2016-03-21 09:26 UTC
