### ISSUE TITLE
missing link to addressbook shared with me

### ISSUE THREAD

**Issue by brianjmurrell** [owncloud/contacts#780] opened 2015-01-15 13:18 UTC
If a user has an addressbook and he shares it with me, I can see it on the web interface contacts editor but when I look at the configuration for it I am missing the ability to get a link to it so that I can view it from a carddav client.

That makes the ability to share addressbooks of pretty limited use.  The web interface is almost a non-use case.  Everyone wants the carddav access.

**Comment by jbtbnl** [comment] 2015-01-15 18:09
Duplicate of https://github.com/owncloud/contacts/issues/701, a fix is ready for review: https://github.com/owncloud/contacts/pull/773

**Closed by jbtbnl** 2015-01-15 18:09 UTC
