### ISSUE TITLE
Croatian (native) characters are not displayed

### ISSUE THREAD

**Issue by gour** [owncloud/contacts#191] opened 2016-03-11 10:02 UTC
### Steps to reproduce
1. none of the contact entries which contain Croatian characters (čČ,ćĆ,đĐ,šŠ,žŽ) are displayed neither in the main contacts list nor in the entry's fields.
### Expected behaviour

Tell us what should happen

To have all the characters rendered.
### Server configuration

**Operating system**:
Linux Fedora (iirc), it's at Webfaction hosting provider: 3.10.0-327.4.5.el7.x86_64 

**Web server:**
Nginx as reverse proxy and Apache

**Database:**

MySQL.

The entry should look like: Saša Janiška, but it renders as:

![owncloud-contacts](https://cloud.githubusercontent.com/assets/114592/13698756/68e6f480-e776-11e5-921c-c58906b7b8b0.png)

**PHP version:**

PHP-7.
**ownCloud version:** (see ownCloud admin page)
9.0.0

**Contacts version:** (see ownCloud apps page)
1.0.0.0
**Updated from an older ownCloud or fresh install:**

updated from 8.2.1
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

Enabled:
- activity: 2.2.1
- calendar: 1.0
- comments: 0.2
- contacts: 1.0.0.0
- dav: 0.1.5
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_pdfviewer: 0.8
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 14.5.0
- notifications: 0.2.3
- provisioning_api: 0.4.1
- systemtags: 0.2
- templateeditor: 0.1
- updatenotification: 0.1.0
  Disabled:
- encryption
- external
- files_external
- user_external
- user_ldap

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

{
    "system": {
        "instanceid": "oc9ff61be09a",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "oc.atmarama.net"
        ],
        "datadirectory": "\/home\/atmarama\/repos\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/oc.atmarama.net",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "net_owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "singleuser": false,
        "theme": "",
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": true
    }
}

**Are you using encryption:** yes/no

no

### Client configuration
**Browser:**

Firefox (Iceweasel 44.0.2.)

**Operating system:**
Linux Debian Sid
```
#### ownCloud log (data/owncloud.log)

```
[...]
{"reqId":"p3Kh7tCeAZ8g5q5YGdSM","remoteAddr":"","app":"core","message":"starting upgrade from 8.2.1.4 to 9.0.0.19","level":0,"time":"2016-03-11T09:15:37+00:00","method":"--","url":"--"}
{"reqId":"p3Kh7tCeAZ8g5q5YGdSM","remoteAddr":"","app":"core","message":"No update found at the ownCloud appstore for app 166054","level":0,"time":"2016-03-11T09:15:48+00:00","method":"--","url":"--"}
{"reqId":"VuKM78kqXxhiYdRqGeJc4gAAAAA","remoteAddr":"109.227.32.95","app":"PHP","message":"Undefined index: newVersionString at \/home\/atmarama\/webapps\/net_oc\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-11T09:16:31+00:00"}
{"reqId":"VuKR55cpDprJqLTipCuf9AAAABA","remoteAddr":"109.227.32.95","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 405 The resource you tried to create already exists\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\MethodNotAllowed\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/atmarama\\\/webapps\\\/net_oc\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(590): Sabre\\\\DAV\\\\Server->createCollection('Notes', Object(Sabre\\\\DAV\\\\MkCol))\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMkcol(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/home\\\/atmarama\\\/webapps\\\/net_oc\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/home\\\/atmarama\\\/webapps\\\/net_oc\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:MKCOL', Array)\\n#4 \\\/home\\\/atmarama\\\/webapps\\\/net_oc\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/home\\\/atmarama\\\/webapps\\\/net_oc\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/home\\\/atmarama\\\/webapps\\\/net_oc\\\/remote.php(138): require_once('\\\/home\\\/atmarama\\\/...')\\n#7 {main}\",\"File\":\"\\\/home\\\/atmarama\\\/webapps\\\/net_oc\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":1121,\"User\":\"predrag\"}","level":4,"time":"2016-03-11T09:37:43+00:00"}
{"reqId":"VuKTfA3rvkfqQCquaPdopAAAAAM","remoteAddr":"109.227.32.95","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 405 The resource you tried to create already exists\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\MethodNotAllowed\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/atmarama\\\/webapps\\\/net_oc\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(590): Sabre\\\\DAV\\\\Server->createCollection('Notes', Object(Sabre\\\\DAV\\\\MkCol))\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMkcol(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/home\\\/atmarama\\\/webapps\\\/net_oc\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/home\\\/atmarama\\\/webapps\\\/net_oc\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:MKCOL', Array)\\n#4 \\\/home\\\/atmarama\\\/webapps\\\/net_oc\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/home\\\/atmarama\\\/webapps\\\/net_oc\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/home\\\/atmarama\\\/webapps\\\/net_oc\\\/remote.php(138): require_once('\\\/home\\\/atmarama\\\/...')\\n#7 {main}\",\"File\":\"\\\/home\\\/atmarama\\\/webapps\\\/net_oc\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":1121,\"User\":\"predrag\"}","level":4,"time":"2016-03-11T09:44:28+00:00"}
{"reqId":"VuKUD5no7Bk3Mf@CXZqG4QAAAA8","remoteAddr":"109.227.32.95","app":"PHP","message":"Undefined index: newVersionString at \/home\/atmarama\/webapps\/net_oc\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-11T09:46:56+00:00"}
```

**Comment by Henni** [comment] 2016-03-11 10:07
@gour could you attach the vCard, please?

**Comment by gour** [comment] 2016-03-11 10:11
@Henni you mean real vCard file or shot?

**Comment by Henni** [comment] 2016-03-11 10:12
Either paste the contents of the vCard or make a screenshot of it.

**Comment by gour** [comment] 2016-03-11 10:32
Here is the vCArd as exported from the Evolution (just changed some non-important data):

```
BEGIN:VCARD
VERSION:3.0
UID:8a54307d-8dfa-4d3d-8773-1dcf1d7687df
X-EVOLUTION-FILE-AS:Saša Janiška
FN:Saša Janiška
N:Janiška;Saša;;;
PHOTO;ENCODING=b;TYPE=jpeg:/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQEC
 AgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2w
 BDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoK
 CgoKCgoKCgoKCgr/wAARCABgAGADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAw
 QFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0Kx
 wRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3
 R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW
 19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQ
 oL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAV
 YnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eH
 l6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna
 4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD9Wvh58ZfHknhPSWk8Q/8AMOtv3H2SH/
 nin/A6TU/FMlxcvcT28VrL/wA9rGB4Xm/39j1veGvgf4W8PfD3SZH1HVryX+yrby7WC3R/+WKf
 7GxKh/4Qhg7/AGP4Zaq6/wDTe68n/wBk/wDZ6+rw+Kyr46UP/SIH8/ZllnFEPcxdbn/8Dn/6Rz
 8hy8899dxi6urzz5fSen1vv8FfG/8A0Js2P+u8P/xdUPEfgbxP4N0SbX9atUsLCxgeW9vr6+hR
 IUT77u7vsRK9eOMwXwwnD/wM+Xq5HnEPfnhp/wDgEzJgCRR/KKI/M/5aQ4NeCfEX/go/8OtB+0
 ad4N0q/wBcl/5YT/8AHvb/APfb/P8A+OV594a/4KZePdOvbj+3/AGm38H/ACwgsZprd/8AY+d9
 6f8AjlfV4Xg3iLEUfawwn/gfxngyx2EhPk5z68t/LkjyJN1TV8k6Z/wVa1+9u4tbi+CVhNpNzs
 l+wz6hMlxMj/8ATZE2J/3xX05+zH/wUV/ZS+MGo2/habRZfCutXciW9rZ61a71mmf+BLhN6PvP
 yJv2O7/Js3/JXkZ5k+f5BhPrFbCTnD+5yT5P/AD2sgw+W51X9lLFwoz/AL/P7/8A7Z/5ObVFe9
 eJ/hv4U1mzFvN4cgjftJAiIyf7leeeMf2fNVsXj/4RCOS/i8t/M8+SFHh+5s2f+P181guIcLW9
 2fuH0+b8AZxl0Oej++h/c+P/AMAOQ8P2aJYvfoN8sZ2itxFiVCbiX7n+sTy6qTeBfF3gWMSSeH
 551m/54fP/AOgfcerun+HvHmsQP9j8H3FpvH7t719n/jn3/wDxyv8APTxl8BfE3irxeqZ7k9WE
 8PWnRnDE+2hD2PJCEPg5+f3Jw54ckJ/+Bn6/wVxLk+VcNf2Zi8PP20Ofnh7Gf77n/wC3OT3/AO
 +ZvgL46+NR4G0nzdUiX/iXW3+og/6Yp/f31NJ8W/iCU2S+JJPxgRP/AEBK5D4ef8iFpf8A2Drb
 /wBAStWv9HIZbgoQ/gwPwOvn2dyn7+In/wCBzNiP4zeNZ/3L+Lpf9z7In/xFfLn/AAVN/ao168
 8NW/wNtvGH2i3vwl14ggFsmSiPvhhfYn8bpv8A+2Kf369s+IXj/RPhn4TvvGfivWfs+n6ba+bd
 /u/n/wBxE/jd/uIn8b7K/Nr4tfEvx58bviFfeLtf1D7BPf3f2u++5LcQ233IYfuOiJ8mxNm/5E
 d96OlfV8A8PQx+dwxs8PDko/8Apf2Psf458/P7nufHznmZnnmaTwk6M8TP3/78+Tk+39v/ALc+
 Al8v/psPyrJm8ZeDPnsv+EisP/A1E+R/40ff/wCPpUo8K6ZqK4vxcX//AF3Hy/8AflERHf8A23
 R3SpYbaMau/wDZ/wDr/svlTwfx/I+9P++N83/fdf0jKVY+B/clW08Z+DNOH9n6d4l0b7Pbf6j/
 AE2H/wCLq/pmqaXq0b3+iajv+z/8toJ/9S/++n3HqxHcVkeKvDo1Gw+3j/kIW372CeCbY/8Aub
 0+fY/3H/36jklCn74Q9nM/Sv8AYc/bZ+I37Q3gD7JfXXm+ItIZLfUI4rWP9912XL/wJv2P/cTe
 j/7FfQ/ghvipeweZrWneS8f/AD9Xqf8AoEKIlfkl/wAE+f2ntX/Zu/aDsfFX2r7RoGrf6LevcJ
 sm+wXDp8+99m/7O/ku+9N6J/G7vsr9RJP2jtb8vadGgWv5J474UrZXm84YHDw9jP34f/If+B/+
 Sch++cK8R4RYaGIzLHVuf+T7B7NFDeDlpT/37/8As6s+T/00rxH/AIaa8Zf9Am0/8ep3/DTHjD
 /oFW35PXxf9g5j/Ifcf8RB4Zh9uf8A4BM86+Emg3Wr+DtJsdJ07zZBocP3P9xK2bnwdr+nWjXd
 /wCGLnyrZHl+4/3F+9/+xXqfw7sfCHw8+HmmRacdJ0q4n0uGK1nuJEi86byfkT+DfXHfB74+X+
 ra0PC3xC1WC4gvv3UE88CJsf8AuPsRE2P9z/frsnxFW5/ch7h4eH8MqHsP3uI9/wDufAfnJ+1b
 8Uvih+0N8Rbfw/deENX022tp/wDiUeGfsU32iZ/+ezps3u7/AOxv2J8ifxu/rX7MX/BKG71Kb+
 1/jvcz2D3P/Mv6c6faP+3iZN6J/uJvf/bT50r7j0z4MeFvDd/Lqt3rMrfu/wBzBL9yH/4uoNTi
 /wBLli8rYlTxN4uZ1l9ClkmSUYYfDcnxw+Pn5/fh/c+OE+f4/wC/A6OB/CXBTrTxue/vp/yfY/
 7f/n/wf+Bnk/wn/wCCUX7JumXn9tar8MWu44R+4t77VLl4pn/203/On+w++vdrP4K+BfCPhn/h
 F/A/hOw0e1h+5a6bB5Nv/ubErT+FdzYDRBZ2w/ews/mVy1z8LPDXw3+I/iH40WXiDWpdb8WabY
 afd2M+r3Eunwpaed5LxWjv5ML/AL197oib/wCOvlK+b43Osr581xE63ufbnOf/AKWfo+FyjAZR
 j+TLMPCj7/2IQgVPiF+xr8APikYtU+Jvwj0jWr9B/wAhGe12XGP7m9Pn2f7FeZ/GH/gmx+zN4h
 0h9Oi+DNhp8cv+pvtGj+zXFs/+8nyP/wADR0/vpXrPw9+E/hS0+KuvfHPSNe8Qza34l0uwsNVs
 Z9ZuJdPtktPO2PDaO/kwu/mvvdE3vW58TL+CGCLT3k+bzd1L+28bgMvhPA4ucIQ+DknOHIVHI8
 txmNnHF4SE+f4+eED8uv2iP+CWvx58EXfn+BtEPijT7YvLBfWWz7QyfxpLbO6O+/7myF3/AL/y
 bPk9Y/4J4zfH218Oz+DPGPwc1u08P6XA4srzUbX7P9m2fftnSbY7p/c2I+zY6P8AJs2faXgSyf
 UL+OOeTc9dTr/hjRL/AEeTSNQhCWXk/Psm2fJ/wCvo8H4vcRcQYSrgc1w9GcIcn7734T5/t+5z
 8nP/AIOT7z85zjwgyPB472uCqzh/c+x/4H8fJ/j5zwKzS6u5/JtdO8ySb/UQQVa1zwxq3hZIv7
 X0KW3877nl/wD2FUvCmuT2/jGxfSLz7Oj6kn7+fZ9x/kd33/wbN9e7vovhH4m6TBPcWQuLDzPN
 j/f/AMf3Pvo/+09eriOI6cMVyQh7h89gvDbE1sr9rVnyVvsQ+x/2/wD/AGh5/wDHjQdPHwR0Xx
 df+KrCwt9K02EH+0Zkt4pklSFNm9/k370TYn8f3K8S0r4keDdRvrfT9O8b6NcXFz/qIIL2Hf8A
 8ATfvr6K8ZfBbwf8f/2f7H4f+L5p/sNzo1nL5tj9+F0RHR0+/wDP/sfx1+b2g+JbP4WfEL7f4V
 E9/BYTvF/xOLH7Pcfxo6PCjv5L/f8A432f+OV8wfuR+k3g/wDaM+HvifR7dfEmopb3uz9/Bd27
 7N/+w+zZU2raVb6jbS6v4Z177ZYfx+RP5uz/AIH/AJ2V8p/CH45+DPimG07S/Pt7/wD5b6dP/w
 Cho6fI6f8AfH+5WP8ADD/gqz+x18NfH2u/Cv4jfFHxP4B8S6bq0ulXv/CQaJ/xL5iD+7nSaFLl
 Nmx96PN5P+2ib9j+Fmn9nTp8mLnyfyDwEsVCpz0oc59DeBdF8c6f4mvrjX9RgSz/AOXGCD+Ctf
 xB4l0jw55X9t+MLC33/wCvjnmRN/8A329YHwC174e+Lvh7b3Hwl/aEtfiPpELlP7Zi1a2vn4H3
 HuLXepf/AG5XR/v73rx3/grF+zx4Z+OXwSmm8Ux2Fq3huN5ZLjUdCmuXhhdGR3T7NDM7In3/AJ
 EdPk+fZ99Pn6uS42E+XD/vofY5Pt/9uH1WFzTLsxxMPrtWGH/n5/se5/X/AKWfQ2gXmkahbeZ4
 ckguLJP+W8E+/wD8fSue8Xp4s1Dxtp+naJrMFvazf8fUfl/fqn+yR8I0+DPwb0TwJpGm/avscH
 7/AOw6b9iijmf523+ds2P8/wBzZv8A76I/yVh/tT/Gv4B/Cae0X4pft22fwvuoNRhu0sbTXbBL
 i9aF0dIXimhe4mTfsR0RPn37H30sLktec/3s/ZQ/nn9gwxGc4TLalX6p/tHx8nJ9v+/7/wD4Ge
 46XY6d4C0+11XW/EUWnNN/ywm/ufxIif3/ALn+5WD8XPj74Mv/AAld+H/Cmo/bLi/g8nzPLdER
 H+/87p/cr5e8H/8ABRD9nf8Aax+Md94Z+CHxC13xK9tpT6jdau+gzWmn2aI6IkKPcuk293m+RP
 J2bEd9/wDfg+Kv7RmgfDy8uPDml6bcalq1t/yw/wBSkP8Avu//ALJv/wCAV9Nlv1JYT/ZZ88D5
 zFSrzrc9X4zqJvih4C/6Kbo3/g0h/wDi6+nvgd4eHg34Y2F1p2owX8c//EwuJrCdJYpkdOsTp8
 j/ACbH3/x/8Dr83Pg94Y0r4w/F2w0Txpd3lnb+IdS/fvo9sjPvmf8AuO6eSifO7vsfYnz7H+ev
 1G8CeC/Dfww8G6f4Y0CFbfStHsUig+b+BE2fO/8AHXsCOS0TxnrWmeEtJ07T9lv5Om23/olP79
 cr+1X+yLY/tC+AXXwzqOhx+JRcqf7Z1HQbO4e5Tbs8l5vJ3w/wPvT502fx10/w9vNA1yw0n7X/
 AMe/9h23/bZ/JT/P/AK7e1n8BBP3f9m/+OUAfmp8WfgD8X/2QfFNidR8RRSz6wn7j+w57l/tSI
 /3Hea2RN/+wju6ff8Ak3pXyH/wWJ+CXj7UPiLH+0t/wofVtG8PeILWG01XUJ4H2Q38O9E3vsT7
 8KQ7HdER3R03u9fu7P458M6ciebrO/8A65wPXyb/AMFk9X0hP2GfiZfa14IuNZim0LyktLXZvg
 meaFIbl/n+5DN5Mz7N/wAkNfJcTYX61k84cn9//Byf1yHXkkuTG/H/APbn4X+FPE/iLwTrVv4t
 8I+JtR0jVrb/AFGoaNevb3EP+5NC6On/AAB67Pxn/wAFcv8Agod4ZT/hFNH/AG1/Fq2um+Slp9
 paG4f/AH3mmR5nf76b3euNrzX4xwk6vc++nJ/7P/8AEV+TZDisThq/7uXIfZY3C050/fge8ap/
 wUR/bT+Ofhn7L4//AGu/FtxBb/uprX+1JrG3mT5H2PDa7EfZu/jR685t/DPkyZWP+/5/8H/A/k
 +46Vl/BuHyfC2P+nv/ANkSt54u2PwrHMsRWqYid585rh4U4U/cPvX/AIJHfD/x3+zz8A9f+Jo+
 Bms/8VzP/wASrWfIfZ9jh8798nyPsTzpnf59iP8AJs3olfQ3wO/ZC+Mf7U9reeOrDxtpTslx9k
 vX16e8SXfs/g/0Z0dNn8CP8n+xXgP7Wn7ZfjH9sf8AYC0j4B+B/h7qHg+8trLT4tetNRmRIb+2
 sYfktodj79k0yQunnIn+p2bPn319O/8ABLH/AILSfAf9oW48G/sv+H/hN400S4sPC1tYWOo6/q
 Nte/aprazTennI++5+4/77Ym/77om99n6bw9xFlNWP1CE/g5If45z/APkz5fM8mzGE/rEofH7/
 AP25/wDaH1/8Cf2YvCfwU8CW+h6lYaPPqaQv9t17TdEttOeb/vyifIibU+ffv2b3q3/bOt6jb2
 +kfZk8r/nh/wA9v/2K1/F3xEXUbJrOwH+j/wDLeetvwF4Zi0HT/tMv+vueuf8A0CvvzxTC+E3w
 z0SDwJpP2yLz2/sq2/2P+WKf3K1dT+HHh/7G50+H7PJ7T/8Aoe+uM8Fa7f8Ai7QdC0TTw9vbf2
 dbf+iU+d69N0TRdP06w+x2ca+VQB5rXBftI/Cnxh8ZfhzqPwx0Dxvo2jWGsadNp+qf2j4d/tDz
 raZNjoifaYUT5Hf76P8A8Ar2u8tvDFpff2Jq2hQQfaf9RP5HyP8A8D/gesaH4Z67HdYzBb2//P
 bz645Q5zngfmdo3/BrToa6RLCf23/EFxPJ/qbjUPCFtgf76QzJvT/YDo/+3Xz38f8A/g1//bkv
 vEstr8PfEfgrX9Ka22wXsmtvaP1f78Lw/I/zfcR3T/br93fDesWGo2n+hyJth/df/EVX18Xd5r
 1lY28qrHDJ9on/AOAV4lXh3KVU9pCjyf4D0YZtmEKfJKfOfiX+zj/wbGftezt9h+LfxD8H+ENP
 E+5p7O9m1K4HC/ct1REdOD9+ZP8Acr2s/wDBtP4V0kC50v8AbQ8R2l/aTeZ50Xhi2Y70/jT99/
 f+f/0Ov1l7fh/Ws6+8G+HtQj/5Bypj/ng+z/0CsqPDGTR/eTpc/wDjKlmuYz+2fnJZf8EKdP17
 /iTePf20vF1/p9x+6ng0jSdP097zf/A8yI77H/jRNm/+/XoX/BMz/gi1p3/BO34j6n450n9p7x
 D4qttQtTENEksPslp5g/ikRJnSXZ67EfeiHf8AwV9Xf8Iff2fiCO5jt1+xpep5En/A/wDf313j
 LIBxxVYfhvKMBGDw+H5P8Aq+Z5hiP4tbnKtr4Y0Sy/49PDlun+5AlP1fXrDQI91/e7Kdqeoxab
 Y3F/d/dhrzLWtUv9dvvt12P8/3K+qOU//Z
PRODID:-//ownCloud//NONSGML Contacts 0.3.0.18//EN
REV:2016-01-29T09:33:54+00:00
X-EVOLUTION-WEBDAV-HREF:https://atmarama@oc.atmarama.net/remote.php/carddav
 /addressbooks/atmarama/contacts/8a54307d-8dfa-4d3d-8773-1dcf1d7687df.vcf
URL:http://www.atmarama.org/
TITLE:
ORG:Atmarama d.o.o.;;
ROLE:savjetovanje
X-EVOLUTION-MANAGER:
X-EVOLUTION-ASSISTANT:
NICKNAME:Gour
BDAY:1964-11-18
X-EVOLUTION-ANNIVERSARY:2000-10-20
X-EVOLUTION-SPOUSE:
NOTE:vrijeme rođenja: 00:00\nmjesto rođenja: City\ninicirano ime: 
X-EVOLUTION-BLOG-URL:http://www.atmarama.net
CALURI:
FBURL:
X-EVOLUTION-VIDEO-URL:
X-MOZILLA-HTML:FALSE
ADR;TYPE=HOME:;;Hlapičina 214;Sveti Martin na Muri;Međimurje;40313;Hrvatska
LABEL;TYPE=HOME:Hlapičina 214\nSveti Martin na Muri\, Međimurje\n40313\nHrv
 atska
EMAIL;TYPE=HOME:gour@atmarama.net
EMAIL;TYPE=WORK:email@domain.com
TEL;TYPE=CELL:+385 95 000 00 00
TEL;TYPE=WORK,VOICE:+385 00 000 000
X-EVOLUTION-WEBDAV-ETAG:"ded100582f69fb8b743bfda76ed45b54"
END:VCARD
```

**Comment by Henni** [comment] 2016-03-11 12:01
I added this vCard to my owncloud instance and it seems to work for me:
![image](https://cloud.githubusercontent.com/assets/1267827/13701584/3655bd9a-e789-11e5-8ef0-ec79dfca5710.png)

@gour which browser do you use?

**Comment by gour** [comment] 2016-03-11 12:14
@Henni Firefox (Iceweasel) 44.0.2 under Debian Sid

Indeed, with Epiphany & Chromium Version 49.0.2623.87 built on Debian stretch/sid, running on Debian stretch/sid (64-bit) it works.

**Comment by Henni** [comment] 2016-03-11 12:20
Good to know!
I'll test it later with Firefox

**Comment by irgendwie** [comment] 2016-03-11 13:31
Not reproducible with Firefox 45.0 and Chromium 49.0.2623.87
@Henni can't reproduce this problem either.

@gour Have you tried opening it in a private session window in firefox?

**Comment by DeepDiver1975** [comment] 2016-03-11 14:00
Looks like to be an environmental issue ... maybe some language pack missing on FireFox?

I tend to close this ....

**Comment by gour** [comment] 2016-03-11 14:31
@irgendwie Same problem with private window session.

**Comment by gour** [comment] 2016-03-11 14:34
@DeepDiver1975 Let me just say that the contacts were displayed properly with the same version of Firefox and Owncloud-8.2.1?

**Comment by DeepDiver1975** [comment] 2016-03-11 14:35
> @DeepDiver1975 Let me just say that the contacts were displayed properly with the same version of Firefox and Owncloud-8.2.1?

strange

**Comment by gour** [comment] 2016-03-11 15:03
When I tried to inspect element in Firefox showing just my name and changing the 'font-family' in inputs.css:38 from 'inherited' into e.g. 'serif':

```
input[type="text"], input[type="password"], input[type="search"], input[type="number"], input[type="email"], input[type="tel"], input[type="url"], input[type="time"], textarea {
    background: #fff;
    color: #555;
    cursor: text;
    font-family: serif;
}

```

it fixed rendering.

Any hint?

**Comment by DeepDiver1975** [comment] 2016-03-11 15:07
@jancborchardt we need your insights into font fun regarding this issue - THX

@gour maybe there is a font missing on your system?

**Comment by gour** [comment] 2016-03-11 15:24
@DeepDiver1975 it looks something is wrong with the stylesheet, iow. even when I explicitly change 'font-family' to:

```
input[type="url"], input[type="time"], textarea {
    background: #fff;
    color: #555;
    cursor: text;
    font-family: 'Open Sans';
}
```

it renders properly, which proves that font is there, but something is wrong with CSS cascading.

**Comment by DeepDiver1975** [comment] 2016-03-11 15:26
Okay - we need some CSS wizards here @jancborchardt @Henni THX

**Comment by Henni** [comment] 2016-03-11 15:55
sorry, no idea.
@jancborchardt any idea what could cause this?

**Comment by jancborchardt** [comment] 2016-03-18 14:46
Hm … I have no clue here either.

@gour when you inspect the field, does the value have the correct name with the special characters?

And does the issue also occur elsewhere in ownCloud, like in the users management?

**Comment by gour** [comment] 2016-03-18 15:25
@jancborchardt It is present with e.g. user's Lastname, then in Calendar for the entries containing native chars etc.

I'm not 100% clear what do you mean with "does the value have the correct name with the special characters?" since e.g. for address field, the value is pulled from the following code:

```
<input class="ng-pristine ng-valid ng-not-empty ng-touched" id="details-address" name="address" ng-model="ctrl.data.value[2]" ng-model-options="{ debounce: 500 }" ng-change="ctrl.model.updateContact()" value="" focus-expression="$parent.ctrl.focus === ctrl.name" type="text">
```

**Comment by jancborchardt** [comment] 2016-03-19 06:35
@gour I mean when you right-click the field in your browser and use »Inspect«, you will see the code. Does the name show up correctly there? Or is it also cut off?

@Henni @irgendwie so what’s the difference between this field and e.g. the Name field in personal settings?

**Comment by gour** [comment] 2016-03-19 08:03
@jancborchardt I bet that now you can see, based on the pasted code above that the name is shown correctly, right?

```
name="address"
```

**Comment by DeepDiver1975** [comment] 2016-05-30 06:26
I'm closing this because we cannot reproduce this and have no idea on how to fix it. Sorry

**Closed as completed by DeepDiver1975** 2016-05-30 06:26 UTC
Labels: bug, needs info
