### ISSUE TITLE
[OC 7.0.1, FF 31.0] Loading Contacts App yelds "Unresponse Script" message (~700 contacts)

### ISSUE THREAD

**Issue by tHeCh0s3n0n3** [owncloud/contacts#576] opened 2014-08-05 11:27 UTC
CLOSED AS DUPE OF https://github.com/owncloud/contacts/issues/582

Summary
------------

When loading the Contacts app, the "All" section is selected. The issue is that it hangs the browser until it is finished loading all the contacts. In FF, execution of the script is interrupted and the "Warning: Unresponsive Script" dialog box shows up with the following Text:

    A script on this page may be busy, or it may have stopped responding.
    You can stop the script now, or you can continue to see if the script will complete.

    Script: https://owncloud.devtf.com/core/js/jquery-.10.0.min.js?v=970627414218ccff3497cb7a784288f5:6

What is expected
---------------------
The Contacts app shouldn't hang the browser while it loads the page.

Steps to Reproduce
-------------------------
#### Using FireFox v31.0
1. Have 700 contacts in OwnCloud
2. Click on the Apps icon
3. Click on contacts
4. **Wait while browser becomes unresponsive**
5. See "Warning: Unresponsive Script" message

#### Using Chrome 36.0.1985.125 (stable)
**Can not reproduce on chrome**

Environment
----------------
* OS: Ubuntu Server 12.04.4
* OC: 7.0.1 stable
* Web Server: 
    * Apache 2.2.22
    * PHP 5.3.10
* DB: MySQL 5.5.38

**Comment by rvega** [comment] 2015-05-13 17:45
+1

**Comment by jetojedno** [comment] 2015-05-25 20:05
+1
issue still present. 3,500 contacts on 8.1 & FF.

**Comment by jancborchardt** [comment] 2015-07-01 10:56
What’s the current status on this? Seems to be something we need to fix for 8.1 @ChristophWurst @DeepDiver1975 @LukasReschke

**Comment by DeepDiver1975** [comment] 2015-07-02 11:12
> What’s the current status on this? Seems to be something we need to fix for 8.1 @ChristophWurst @DeepDiver1975 @LukasReschke

as already stated somewhere else - we need a proper lazy loading mechanism. This is not inserted easily -> 8.2

**Comment by jancborchardt** [comment] 2015-07-02 11:18
Closing as duplicate of https://github.com/owncloud/contacts/issues/582 – which has more info on the topic.

**Closed by jancborchardt** 2015-07-02 11:18 UTC
Labels: 1 - to develop, bug, priority
