### ISSUE TITLE
Groups visible on OSX/iOS but not in the Web-If

### ISSUE THREAD

**Issue by ArnaudFeld** [owncloud/contacts#956] opened 2015-07-02 11:39 UTC
I have 3 Groups in my Adressbook on OSX/iOS. Everything Works but when i look over the Web-If i see there are no groups, but i see the Group-Name as a vcard (like in the Screenshot the Group "Privat" is shown as normal entry.

iOS & OSX running 10.10.4
Owncloud running 8.0.4

Any other Informations you need?

![bildschirmfoto 2015-07-02 um 13 36 57](https://cloud.githubusercontent.com/assets/1561416/8476209/7425dbc8-20bf-11e5-86e3-c482f7d871d2.png)

**Comment by jancborchardt** [comment] 2015-07-02 13:20
@babelouest @LEDfan any idea about this? Which other info do you need?

**Comment by babelouest** [comment] 2015-07-04 19:19
A sample version of the VCards would be helpful to understand what's happening, and also a little bit more of information because I'm not sure I understand the problem here...

**Comment by ArnaudFeld** [comment] 2015-07-04 20:41
Here a sample:
BEGIN:VCARD
VERSION:3.0
PRODID:-//Apple Inc.//Mac OS X 10.10.4//EN
N:for Github;Test;;;
FN:Test for Github
TEL;type=CELL;type=VOICE;type=pref:+49 800 1234567
CATEGORIES:Privat
X-ABUID:83B24654-AF9F-4805-8A61-EE6D7A92F2AA:ABPerson
END:VCARD

Here more Informations:

i'm using 3 Groups (in the vCard called CATEGORIES): example.: Privat, Work & VIP are the 3 Groups.
![bildschirmfoto 2015-07-04 um 22 38 36](https://cloud.githubusercontent.com/assets/1561416/8509324/82855790-229d-11e5-9b32-82b187226cf2.jpg)


I see the different groups in OSX and in iOS but the Web-If doesn't show them.

It shows the groups in the Web-If as a own contact what is still wrong.

For  me it seems that the Owncloud ignore the Groups.

Now more clear what i mean?

**Comment by childnode** [comment] 2015-07-18 16:06
ack, same here with owncloud 8.1.0 
a Apple contacts group is defined by a vcard entry

```BEGIN:VCARD
VERSION:3.0
PRODID:-//Apple Inc.//AddressBook 9.0//EN
N:Any Grpname;;;;
FN:Any Grpname
X-ADDRESSBOOKSERVER-KIND:group
X-ADDRESSBOOKSERVER-MEMBER:urn:uuid:6fbc403d-3eea-4c25-990f-e948e8208acf
REV:2015-07-18T15:29:52+00:00
UID:695aada7-c4f7-4f2d-af81-e56f1b2439db
END:VCARD
```

which entitles the members list, the member is:

```
BEGIN:VCARD
VERSION:3.0
PRODID:-//ownCloud//NONSGML Contacts 0.4.0.0//EN
N:MAc;test;;;
FN:test MAc
EMAIL;TYPE=pref:023234
REV:2015-07-18T15:32:19+00:00
UID:6fbc403d-3eea-4c25-990f-e948e8208acf
ORG:Foo
END:VCARD
```

while members and groups by owncloud are marked by property `CATEGORIES:another groupname` entry at the "member" as said above and groups are "implicit" objects

**Comment by childnode** [comment] 2015-07-18 20:57
ahhh ... DUPLICATES issue #266

**Comment by jancborchardt** [comment] 2015-07-20 11:51
@ArnaudFeld @babelouest can you confirm if this is a duplicate of #266? If so let’s focus on that and close this here.

**Comment by babelouest** [comment] 2015-07-20 13:01
This looks like a duplicate indeed. There is (was ?) another problem with OSX users, where its contact app was able to see the first addressbook only, #244 for example

**Closed** 2015-07-20 14:18 UTC
Labels: 1 - to develop, bug
