### ISSUE TITLE
Enable/Disable addressbooks

### ISSUE THREAD

**Issue by Julian1998** [owncloud/contacts#637] opened 2018-02-28 18:57 UTC
At the moment you are only able to create, share and delete an addressbook... But enabling/disabling is very important... Now you are creating an addressbook but it's never used because contacts are only saved in the default addressbook.... so it would also be cool if you are able to set the default addressbook

**Comment by christophefromparis** [comment] 2018-03-07 08:25
Is it not a duplicate of #414?

**Comment by Julian1998** [comment] 2018-03-07 16:53
@christophefromparis Not really... In #414 we are talking about importing an addressbook.
Enabling/Disabling is like showing/hiding contacts from an specific addressbook. You can imagine that like in calendar

**Comment by deMattin** [comment] 2018-03-12 15:52
This GUI issue of contacts app together with the (for me) even more important #414 is the only reason why I haven't ugraded my owncloud so far and am still on 8.2.11.

Owncloud X works much better (I test every new release), but without such basic PIM features, that have been working before, I'm not able to upgrade my personal, productive cloud system.

I really hope, someone will take care of this as I'm not able to enhance it on my own.

**Comment by Julian1998** [comment] 2018-03-13 20:51
@deMattin Don't worry ;) I guess we will repair/renew the gui for the addressbooks flags as next step.

**Comment by Julian1998** [comment] 2018-03-14 14:16
@deMattin Are you using an older version of owncloud contacts? Owncloud 8.x isn't supported anymore

**Comment by deMattin** [comment] 2018-03-14 20:26
This issue is about actual owncloud contacts app.
I have a test setup to see the progress of development of actual owncloud and its apps. But  I'm not using it for my data. 

I still use oc 8.11 because old contact's app don't has the issues mentioned above.

1. For me it is essential to use different address books and to have the option, to switch them on and off.
2. The also essential feature is described in #414. You need import of contacts to a selectable address book to backup, restore and maintain your contacts. Without this, there is no possibility to do this as a user of the cloud.

**Comment by Julian1998** [comment] 2018-03-14 21:21
@deMattin I see! We will implement a simple way to change addressbooks on individual contacts as well as for importing/creating

**Closed as not planned** 2023-03-25 12:26 UTC
Labels: enhancement, discussion
