### ISSUE TITLE
does not import google vcard any more

### ISSUE THREAD

**Issue by bernic** [owncloud/contacts#588] opened 2014-08-08 22:26 UTC
Used to import them in oc6
I reinstalled and brand new oc7 and so hopped that the exact same file that were previously imported in oc6 would be as well imported there. But no it only reports 0 failed 0 success 0 import
as if the file was empty, but if I try to import it back to an emptied google account it works, So the file is definitively ok

**Comment by Yuri99** [comment] 2015-01-10 12:26
Same issue with a file of more than 1.300 contacts from my Android contacts. Error message telling "Invalid VObject, line 7 did not follow the icalendar/vacrd format".
Log file content (not very helpfull):
{"app":"contacts","message":"Sabre\\VObject\\ParseException: Invalid VObject, line 7 did not follow the icalendar\/vcard format","level":4,"time":"2015-01-10T12:03:07+00:00"}
I use the version 7 on a hosted shared environment. PHP 5_4, MySQL 5+

**Comment by Yuri99** [comment] 2015-01-11 11:29
While exporting directly a VCF file from my Google account (through the web interface), and while import the result file to my fresh new installation, I got the following error after a little hundred of contact (on 1379):
{"app":"contacts","message":"\/home\/<my home folder>\/www\/apps\/contacts\/lib\/controller\/importcontroller.php. Line: 177: Nom de fichier manquant dans la requ\u00eate.","level":3,"time":"2015-01-11T11:21:38+00:00"}
Translation: "file name missing in the requ" ...est (?)

**Comment by babelouest** [comment] 2015-01-23 15:42
Can you post an anomized sample of the contact that cause problems ?
Having only the error logs doest not help that much since I don't know what data caused the error.

**Comment by wnadgob** [comment] 2015-01-24 10:08
This has something to do with long fields with non ASCII characters.
I'm not familiar with the vCard format, but it seems that – at least when my Android 4.4.2 exports the contacts to vCard 2.1 – if a field contains a non ASCII character it will exported using the ASCII Hx codes for each char.

For instance, if I define a contact with `the Very Long Streeț no. 999999` as Street and `Big City` as City (notice the **`ț`** instead of `t`) it will be exported as:
```
BEGIN:VCARD
VERSION:2.1
N:B;A;;;
FN:A B
ADR;HOME;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:;;=74=68=65=20=56=65=72=79=20=4C=6F=6E=67=20=53=74=72=65=65=C8=9B=20=6E=
=6F=2E=20=39=39=39=39=39=39;=42=69=67=20=43=69=74=79;;;
END:VCARD
```

When trying to import it using the ownCloud version hosted by owndrive.com the following error will occur:
```
Invalid VObject, line 6 did not follow the icalendar/vcard format
```

As you can see, the address line is separated on 2 lines, the second one being considered invalid.
Also, it seems that there will be an extra `=` (although the fist line ends with one, the second line also starts with one).

One last thing, concerning the line number from the error, I noticed that it is relative to the broken contact not to the whole file (when I had some other well formatted contacts before the broken one, the same line number was indicated); therefore while the issue might be caused by the export, the error reporting can be improved by indicating also the contact index.

**Comment by babelouest** [comment] 2015-07-19 22:53
I'm not sure which PR helped but it seems that this problem is now solved.

I'm closing this issue but if you think the problem remain, you can reopen it.

**Closed by babelouest** 2015-07-19 22:53 UTC
Labels: import
