### ISSUE TITLE
Upgrade Contact app to 0.5.0.0 broken (Owncloud 8.2.1)

### ISSUE THREAD

**Issue by stephane84** [owncloud/contacts#1107] opened 2015-11-22 09:33 UTC
### Steps to reproduce
1. Upgrade owcloud core to 8.2.1 successfully
2. Got to the deactivated apps page
3. You got the message : "This application cannot be installed because of non satisfied dependencies : Owncloud 8.1 or lower is required."
3. Click on the "upgrade contact app to 0.8.1" button

### Expected behaviour
The Contact app is upgraded to a compatible version with oc core 8.2.1

### Actual behaviour
The following error message appears in red : 

Unable to generate a URL for the named route "contacts_index" as such route does not exist.

### Server configuration
**Operating system**: Linux sheevaplug 3.18.0-trunk-rpi2 #1 SMP PREEMPT Debian 3.18.5-1~exp1+rpi19 (2015-08-08) armv7l GNU/Linux

**Web server:** lighhtpd

**Database:** mysql

**PHP version:** 5.4

**ownCloud version:** (see ownCloud admin page) : 8.2.1

**Updated from an older ownCloud or fresh install:** updated from 8.1.4

**List of activated apps:** only the core ones

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
Enabled:
  - activity: 2.1.3
  - files: 1.2.0
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - mail: 0.2.1
  - tasks: 0.8.1
  - templateeditor: 0.1
Disabled:
  - bookmarks
  - calendar
  - contacts
  - encryption
  - external
  - mia
  - notifications
  - provisioning_api
  - updater
  - user_external
  - user_ldap

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
?php
$CONFIG = array (
  'instanceid' => 'oc16982b0ad5',
  'passwordsalt' => 'XXX',
  'secret' => 'XXX',
  'trusted_domains' => 
  array (
    0 => 'XXX',
    1 => 'XXX',
  ),
  'datadirectory' => '/media/donnees/owncloud',
  'overwrite.cli.url' => 'XXX',
  'dbtype' => 'mysql',
  'version' => '8.2.1.4',
  'dbname' => 'XXX',
  'dbhost' => 'localhost:/media/donnees/mysqldb/var/run/mysqld/mysqld.sock',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud_dbuser',
  'dbpassword' => 'XXX',
  'installed' => true,
  'maintenance' => false,
  'forceSSLforSubdomains' => true,
  'trashbin_retention_obligation' => '10, auto',
  'enable_previews' => true,
  'theme' => '',
  'memcache.local' => '\\OC\\Memcache\\APC',
  'loglevel' => 2,
);

**Are you using external storage, if yes which one:** local/smb/sftp/... No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox

**Operating system:** Ubuntu 14.04

**Comment by stephane84** [comment] 2015-11-22 09:35
Related https://github.com/owncloud/calendar/issues/989

**Comment by gvde** [comment] 2015-11-22 09:37
It's a core problem. Thus also a duplicate of owncloud/core#19145

**Comment by RealRancor** [comment] 2015-11-22 11:02
Yes, nothing what can be done on app level.

**Closed** 2015-11-23 08:36 UTC
Labels: bug
