### ISSUE TITLE
Can't add contact in Safari 9+

### ISSUE THREAD

**Issue by jenslauterbach** [owncloud/contacts#332] opened 2016-04-01 13:32 UTC
### Steps to reproduce
1. Open Developer Console in Safari (CMD + Option  + i)
2. Switch to Console tab
3. Open Contacts app
4. Press "Add contact" button
### Expected behaviour

A form should open
### Actual behaviour

Nothing happens
### Server configuration

**Operating system**: [Official Docker Image](https://hub.docker.com/_/owncloud/)

**Web server:** [Official Docker Image](https://hub.docker.com/_/owncloud/)

**Database:** [Official Docker Image](https://hub.docker.com/_/owncloud/)

**PHP version:** [Official Docker Image](https://hub.docker.com/_/owncloud/)

**ownCloud version:** ownCloud 9.0.0 (stable)

**Contacts version:** 1.1.0.0

**Updated from an older ownCloud or fresh install:** Fresh

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Not available in Docker image
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' =>
  array (
    0 => '192.168.99.100',
    1 => 'localhost',
    2 => '192.168.99.100:32768',
  ),
  'datadirectory' => '/var/www/html/data',
  'overwrite.cli.url' => 'http://192.168.99.100:32768',
  'dbtype' => 'sqlite3',
  'version' => '9.0.0.19',
  'logtimezone' => 'UTC',
  'installed' => true,
);
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No
### Client configuration

**Browser:** Safari 9.0.3 (11601.4.4)

**Operating system:** OSX 10.11.3 (15D21)

**CardDAV-clients:** None
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
{"reqId":"th87I5a32Z44exP4rkV1","remoteAddr":"192.168.99.1","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Contacts tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/migration\\\/migrateaddressbooks.php(83): OCA\\\\Dav\\\\Migration\\\\AddressBookAdapter->setup()\\n#1 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/appinfo\\\/application.php(186): OCA\\\\Dav\\\\Migration\\\\MigrateAddressbooks->setup()\\n#2 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/appinfo\\\/install.php(26): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateAddressbooks()\\n#3 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/installer.php(621): include('\\\/var\\\/www\\\/html\\\/a...')\\n#4 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/installer.php(572): OC_Installer::includeAppScript('\\\/var\\\/www\\\/html\\\/a...')\\n#5 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/installer.php(546): OC_Installer::installShippedApp('dav')\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/var\\\/www\\\/html\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(823): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/var\\\/www\\\/html\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/migration\\\/addressbookadapter.php\",\"Line\":72}","level":3,"time":"2016-04-01T12:34:35+00:00"}
{"reqId":"th87I5a32Z44exP4rkV1","remoteAddr":"192.168.99.1","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Calendar tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/migration\\\/migratecalendars.php(84): OCA\\\\Dav\\\\Migration\\\\CalendarAdapter->setup()\\n#1 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/appinfo\\\/application.php(202): OCA\\\\Dav\\\\Migration\\\\MigrateCalendars->setup()\\n#2 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/appinfo\\\/install.php(27): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateCalendars()\\n#3 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/installer.php(621): include('\\\/var\\\/www\\\/html\\\/a...')\\n#4 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/installer.php(572): OC_Installer::includeAppScript('\\\/var\\\/www\\\/html\\\/a...')\\n#5 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/installer.php(546): OC_Installer::installShippedApp('dav')\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/var\\\/www\\\/html\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(823): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/var\\\/www\\\/html\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/migration\\\/calendaradapter.php\",\"Line\":68}","level":3,"time":"2016-04-01T12:34:35+00:00"}
{"reqId":"BdCzllyaC3YbbWAURs4V","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:34:40+00:00"}
{"reqId":"yhyKH9mXRxI\/oduv+Vu\/","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:34:40+00:00"}
{"reqId":"XXhKgLSTU+aN7G+WmXwT","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:34:41+00:00"}
{"reqId":"8C\/1+eyo3vLB2sSEduS1","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:34:47+00:00"}
{"reqId":"XFmEOtXWyCgL+DLTSgZ1","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:34:47+00:00"}
{"reqId":"nLdalZIhrZl0A9LZLyUq","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:34:47+00:00"}
{"reqId":"14+i1behrK\/ZhpKQ68u0","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:34:47+00:00"}
{"reqId":"OnU1klCBVzMUru3GuBtM","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:34:50+00:00"}
{"reqId":"ezOveI\/V9lJpS0iCR\/1C","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:34:50+00:00"}
{"reqId":"6DQMSaT5fL1BrvDK6du3","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:34:50+00:00"}
{"reqId":"vRPRfMCz0Zp1sK2VhoT9","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:34:50+00:00"}
{"reqId":"IHQxknAgLpOf4RkcEYg1","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:37:22+00:00"}
{"reqId":"P\/EHwLBGnOuq2RNeWYhT","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:37:22+00:00"}
{"reqId":"xUvidPBYImivQan9qrty","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:37:22+00:00"}
{"reqId":"3yZgtHm+zOf+aRk0OiEA","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:37:22+00:00"}
{"reqId":"9DHmJzZlzGNT6CvrBovR","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:37:29+00:00"}
{"reqId":"6UUutVUf2Ix\/74nALirN","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:37:29+00:00"}
{"reqId":"GTJ2+fZun5d5Q6D5RC6C","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:37:29+00:00"}
{"reqId":"VoHZWOS+ZSXcrk\/lGSYd","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:37:29+00:00"}
{"reqId":"4+ZQC+Ml0yxQ+GtRg\/sr","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:38:05+00:00"}
{"reqId":"z3cD4QnGpH3UhpyHnoN0","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:38:05+00:00"}
{"reqId":"PDT4P8gpDJuMy9hph49O","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:38:05+00:00"}
{"reqId":"oEEEXIHg7kWu9kOi3i9N","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:38:05+00:00"}
{"reqId":"ZQ3bIs65AGcqBcIH5eh1","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:38:05+00:00"}
{"reqId":"yQVSrWLtfE5F0+T4Onln","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:38:05+00:00"}
{"reqId":"RQw3YM5kgotZGp\/8qgWn","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:38:07+00:00"}
{"reqId":"MstSZuBq3g8IEninudTt","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:38:07+00:00"}
{"reqId":"ohNJVBCu3ulDtUTBUk4B","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:38:08+00:00"}
{"reqId":"BcRaIm5l2j8jTIMVaOWi","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:38:08+00:00"}
{"reqId":"46dtgV9RH3U51CQFvoPL","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:38:34+00:00"}
{"reqId":"+yyCfqMOQ+Ifo4uiGsS\/","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:38:34+00:00"}
{"reqId":"u3EkQEamjDQLB3MFK8s7","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:38:35+00:00"}
{"reqId":"DX5KEdFyx\/hRcbI9z3uN","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:49:00+00:00"}
{"reqId":"2NsQN77+uszZ4xEakf78","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:51:29+00:00"}
{"reqId":"DCGTX5xtsi8GLjufJnfJ","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:51:29+00:00"}
{"reqId":"2gQ6T5NOtahiSWfgRmTk","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:51:29+00:00"}
{"reqId":"+MQwPAfmnJ3PSj+K2zRk","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:51:29+00:00"}
{"reqId":"r8hBhp4Sa7E45hY+S8Nx","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:51:30+00:00"}
{"reqId":"FzcSOlZ7JImhKdEFBeil","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:51:30+00:00"}
{"reqId":"dldJaLImcc8ghR07PAdo","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:56:23+00:00"}
{"reqId":"XwQ1a4bOTFO7tfnm4Euo","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:56:23+00:00"}
{"reqId":"vaMzuGHKi7Gks7pV0fpA","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:56:24+00:00"}
{"reqId":"6pXhwlsK9P59cnUnT71G","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:56:26+00:00"}
{"reqId":"6w2A9VCPOtgzQtmjgP4s","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:56:27+00:00"}
{"reqId":"4MgXb1UXsn78U8F4ppB9","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:56:27+00:00"}
{"reqId":"wfwJowbVfILfBeagGObR","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:56:58+00:00"}
{"reqId":"69O\/3JA8OPLhx9AyNkeq","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:56:59+00:00"}
{"reqId":"mJbmQGc5tdM0QHIdrNbq","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T12:56:59+00:00"}
{"reqId":"MGb4csPb4eT2YNkvF9a5","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T13:04:00+00:00"}
{"reqId":"Wq2oih72z5xpYVx8ik0S","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T13:04:50+00:00"}
{"reqId":"t1QOJuG3nBRtOY+zgfer","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T13:04:51+00:00"}
{"reqId":"otUwTrs8HZTmL1F\/0lMT","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T13:04:51+00:00"}
{"reqId":"TPo4Dw5npzx\/0qQ4C+7X","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T13:04:52+00:00"}
{"reqId":"DQs21OnsJ3NAbr058C4R","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T13:04:53+00:00"}
{"reqId":"uuVXZ0H1TR4Rlvm\/0IBs","remoteAddr":"192.168.99.1","app":"core","message":"Trusted domain error. \"192.168.99.1\" tried to access using \"192.168.99.100:32768\" as host.","level":2,"time":"2016-04-01T13:04:53+00:00"}
{"reqId":"VS7a6ZkSaaEgoR\/bZBH6","remoteAddr":"192.168.99.1","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/html\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-04-01T13:09:58+00:00"}
{"reqId":"rgBAQoO4xogVFeap0OKY","remoteAddr":"192.168.99.1","app":"core","message":"Login failed: 'jens' (Remote IP: '192.168.99.1')","level":2,"time":"2016-04-01T13:11:37+00:00"}
{"reqId":"3TXj\/mplDQoQ5XARz0TF","remoteAddr":"192.168.99.1","app":"core","message":"Login failed: 'jens' (Remote IP: '192.168.99.1')","level":2,"time":"2016-04-01T13:12:16+00:00"}
{"reqId":"u4\/IbCm3wU+rEQzf1Y5\/","remoteAddr":"192.168.99.1","app":"core","message":"Login failed: 'jens' (Remote IP: '192.168.99.1')","level":2,"time":"2016-04-01T13:12:39+00:00"}
{"reqId":"Tt5\/jLbAHbRsHgH4m4Rs","remoteAddr":"192.168.99.1","app":"core","message":"Login failed: 'jens' (Remote IP: '192.168.99.1')","level":2,"time":"2016-04-01T13:12:47+00:00"}
{"reqId":"VNCZqGfZ+Oylcx3hDK9Q","remoteAddr":"192.168.99.1","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/html\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-04-01T13:25:35+00:00"}
{"reqId":"Hfuwk\/BXY5bfpE5d7W+v","remoteAddr":"192.168.99.1","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/html\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-04-01T13:26:13+00:00"}
```
#### Browser log

```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'".
```
#### Reporter notes:

Safari just doesn't want to run the JavaScript (see error above). If I open the page in Chrome it works.

**Comment by aspdye** [comment] 2016-04-01 14:52
I can't reproduce this with Safari on OS X El Capitan. :confused:

**Comment by jenslauterbach** [comment] 2016-04-01 19:51
I also tried it in Chrome and Firefox to no avail.

**Comment by DeepDiver1975** [comment] 2016-04-10 19:37
@jenslauterbach are you still experiencing this? We cannot repoduce and the issue information holds no hint to identify an issue - I fear we have to close this one ....

**Comment by DeepDiver1975** [comment] 2016-04-14 15:43
please reopen if still an issue

**Closed as completed by DeepDiver1975** 2016-04-14 15:43 UTC
Labels: needs info
