### ISSUE TITLE
Search Field in Contacts does not longer work

### ISSUE THREAD

**Issue by blainy** [owncloud/contacts#863] opened 2015-03-26 10:13 UTC
Since i have updated ownCloud from 8.0 to 8.0.2 the Search Field in Contacts does not longer work. It just happens nothing when i enter some Name i am searching for.

**Comment by cova-it** [comment] 2015-03-28 20:53
+1

**Comment by hope55** [comment] 2015-04-06 21:28
The search results will be displayed at the very end of the page, but I don't want to scroll down my 1000 contacts to see the results. The contact list sould be filtered instead. The old dropdown list under the search field was still better than this one.

**Comment by rvega** [comment] 2015-05-13 17:34
+1.  I couldn't find the search results on my 1200+ list until I came here to report a bug and read these comments.

**Comment by bene33** [comment] 2015-06-15 13:15
+1

**Comment by rnalrd** [comment] 2015-10-20 17:18
Same here

**Comment by jancborchardt** [comment] 2015-12-07 08:19
Closing as duplicate of https://github.com/owncloud/contacts/issues/961 – more discussion there, less +1 ;)

**Closed by jancborchardt** 2015-12-07 08:19 UTC
