### ISSUE TITLE
How could the Profile Picture get set in OC9?

### ISSUE THREAD

**Issue by Mannshoch** [owncloud/contacts#410] opened 2016-05-12 17:09 UTC
### Steps to reproduce
1. Wish to add / edit a addressbook profile picture
2. Wonder where to do that
### Expected behaviour

Icons appear near the place where the Picture is
### Actual behaviour

Nothing
### Server configuration

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.6

**ownCloud version:** 9.0.2

**Contacts version:** 1.2.0.0

**Updated from an older ownCloud or fresh install:** Fresh install, Imported Contacts

**Signing status (ownCloud 9.0 and above):**

```
- direct_menu
    - INVALID_HASH
        - css/direct_menu.css
- external
    - INVALID_HASH
        - appinfo/app.php
    - EXTRA_FILE
        - img/SP-Blog.svg
        - img/newsletter.svg
- files
    - INVALID_HASH
        - appinfo/app.php
- mail
    - EXTRA_FILE
        - js/communication.js
        - js/init.js
        - js/ui.js
        - js/tests/Models_Account_Spec.js
        - js/tests/test-main.js
        - js/tests/Views_Attachments_Spec.js
        - js/tests/mocks/OC.js
        - js/tests/index.html
        - lib/service/autoconfig/mozillaispdb.php

```

**List of activated apps:**

```
Direct Menu
Shorten
Mail
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** imap
### Client configuration

**Browser:** Firefox

**Operating system:** Windows 8.1 / Ubuntu 16.04
#### Browser log

```
**From firebug:**

Fehler beim Verarbeiten des Wertes für 'background'. Deklaration ignoriert.

background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#35537...

styles....5a09f84 (Zeile 30, Spalte 13)
Fehler beim Verarbeiten des Wertes für 'background'. Deklaration ignoriert.

background: -webkit-linear-gradient(top, #35537a 0%,#1d2d44 100%); /* Chrome10+,...

styles....5a09f84 (Zeile 31, Spalte 13)
Farbe erwartet, aber 'top' gefunden. Fehler beim Verarbeiten des Wertes für 'background'. Deklaration ignoriert.

background: linear-gradient(top, #35537a 0%,#1d2d44 100%); /* W3C */

styles....5a09f84 (Zeile 32, Spalte 29)
'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden. Fehler beim Verarbeiten des Wertes für 'filter'. Deklaration ignoriert.

filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#35537a', end...

styles....5a09f84 (Zeile 33, Spalte 9)
Unbekannte Pseudoklasse oder Pseudoelement '-webkit-scrollbar'. Regelsatz wegen ungültigem Selektor ignoriert.

::-webkit-scrollbar {

styles....5a09f84 (Zeile 75, Spalte 2)
Unbekannte Pseudoklasse oder Pseudoelement '-webkit-scrollbar-track-piece'. Regelsatz wegen ungültigem Selektor ignoriert.

::-webkit-scrollbar-track-piece {

styles....5a09f84 (Zeile 78, Spalte 2)
Unbekannte Pseudoklasse oder Pseudoelement '-webkit-scrollbar-thumb'. Regelsatz wegen ungültigem Selektor ignoriert.

::-webkit-scrollbar-thumb {

styles....5a09f84 (Zeile 81, Spalte 2)
Unbekannte Eigenschaft 'user-select'. Deklaration ignoriert.

user-select: none;

styles....5a09f84 (Zeile 131, Spalte 12)
Unbekannte Eigenschaft 'user-select'. Deklaration ignoriert.

user-select: none;

styles....5a09f84 (Zeile 262, Spalte 12)
Unbekannte Eigenschaft 'user-select'. Deklaration ignoriert.

user-select: none;

styles....5a09f84 (Zeile 303, Spalte 12)
Unbekannte Eigenschaft 'user-select'. Deklaration ignoriert.

user-select: none;

styles....5a09f84 (Zeile 364, Spalte 12)
Unbekannte Eigenschaft 'user-select'. Deklaration ignoriert.

user-select: none;

styles....5a09f84 (Zeile 408, Spalte 12)
Fehler beim Verarbeiten des Wertes für 'vertical-align'. Deklaration ignoriert.

vertical-align: auto;

styles....5a09f84 (Zeile 413, Spalte 17)
Unbekannte Eigenschaft 'list-style-indent'. Deklaration ignoriert.

... border:1px solid #f00; list-style-indent:inside; margin:0 0 2em; padding:1em; 

styles....5a09f84 (Zeile 418, Spalte 87)
Unbekannte Eigenschaft 'appearance'. Deklaration ignoriert.

appearance: none;

inputs....5a09f84 (Zeile 148, Spalte 11)
Fehler beim Verarbeiten des Wertes für 'display'. Deklaration ignoriert.

display: -webkit-box;

mobile....5a09f84 (Zeile 8, Spalte 10)
Fehler beim Verarbeiten des Wertes für 'display'. Deklaration ignoriert.

display: box;

mobile....5a09f84 (Zeile 18, Spalte 10)
Unbekannte Eigenschaft 'box-orient'. Deklaration ignoriert.

box-orient: horizontal;

mobile....5a09f84 (Zeile 19, Spalte 11)
Unbekannte Eigenschaft 'box-pack'. Deklaration ignoriert.

box-pack: center;

mobile....5a09f84 (Zeile 20, Spalte 9)
Unbekannte Eigenschaft 'box-align'. Deklaration ignoriert.

box-align: center;

mobile....5a09f84 (Zeile 21, Spalte 10)
Name einer Medienfunktion erwartet, aber '-webkit-max-device-pixel-ratio' gefunden.

@media (-webkit-max-device-pixel-ratio: 1.3), (max-resolution: 124.8dpi) {

fonts.c...5a09f84 (Zeile 2, Spalte 8)
Unbekannte Eigenschaft 'user-select'. Deklaration ignoriert.

user-select: none;

apps.cs...5a09f84 (Zeile 30, Spalte 12)
Farbe erwartet, aber 'top' gefunden. Fehler beim Verarbeiten des Wertes für 'background-image'. Deklaration ignoriert.

background-image: linear-gradient(top, rgb(238,238,238) 0%, rgb(245,245,245) 100...

apps.cs...5a09f84 (Zeile 136, Spalte 35)
Fehler beim Verarbeiten des Wertes für 'background-image'. Deklaration ignoriert.

background-image: -webkit-linear-gradient(top, rgb(238,238,238) 0%, rgb(245,245,...

apps.cs...5a09f84 (Zeile 137, Spalte 19)
Fehler beim Verarbeiten des Wertes für 'background-image'. Deklaration ignoriert.

background-image: -ms-linear-gradient(top, rgb(238,238,238) 0%, rgb(245,245,245)...

apps.cs...5a09f84 (Zeile 138, Spalte 19)
Fehler beim Verarbeiten des Wertes für 'text-overflow'. Deklaration ignoriert.

text-overflow: hidden;

apps.cs...5a09f84 (Zeile 271, Spalte 17)
Unbekannte Eigenschaft '-moz-filter'. Deklaration ignoriert.

-moz-filter: drop-shadow(0 0 5px rgba(150, 150, 150, 0.75));

apps.cs...5a09f84 (Zeile 296, Spalte 12)
'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden. Fehler beim Verarbeiten des Wertes für 'filter'. Deklaration ignoriert.

filter: alpha(opacity=50) !important;

apps.cs...5a09f84 (Zeile 339, Spalte 9)
'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden. Fehler beim Verarbeiten des Wertes für 'filter'. Deklaration ignoriert.

filter: alpha(opacity=100) !important;

apps.cs...5a09f84 (Zeile 345, Spalte 9)
'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden. Fehler beim Verarbeiten des Wertes für 'filter'. Deklaration ignoriert.

filter: alpha(opacity=50);

apps.cs...5a09f84 (Zeile 650, Spalte 9)
'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden. Fehler beim Verarbeiten des Wertes für 'filter'. Deklaration ignoriert.

filter: alpha(opacity=100);

apps.cs...5a09f84 (Zeile 657, Spalte 9)
'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden. Fehler beim Verarbeiten des Wertes für 'filter'. Deklaration ignoriert.

filter: progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=...

fixes.c...5a09f84 (Zeile 108, Spalte 9)
Unbekannte Eigenschaft '-moz-box-shadow'. Deklaration ignoriert.

-moz-box-shadow: 0px 0px 20px rgba(29,45,68,.4);

multise...5a09f84 (Zeile 22, Spalte 16)
'none', URL oder Filterfunktion erwartet, aber 'Alpha(' gefunden. Fehler beim Verarbeiten des Wertes für 'filter'. Deklaration ignoriert.

filter:Alpha(Opacity=0);

jquery-...5a09f84 (Zeile 49, Spalte 8)
'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden. Fehler beim Verarbeiten des Wertes für 'filter'. Deklaration ignoriert.

filter: alpha(opacity=25);

jquery-...5a09f84 (Zeile 538, Spalte 9)
'none', URL oder Filterfunktion erwartet, aber 'Alpha(' gefunden. Fehler beim Verarbeiten des Wertes für 'filter'. Deklaration ignoriert.

filter:Alpha(Opacity=70);

jquery-...5a09f84 (Zeile 918, Spalte 8)
'none', URL oder Filterfunktion erwartet, aber 'Alpha(' gefunden. Fehler beim Verarbeiten des Wertes für 'filter'. Deklaration ignoriert.

filter:Alpha(Opacity=35);

jquery-...5a09f84 (Zeile 925, Spalte 8)
'none', URL oder Filterfunktion erwartet, aber 'Alpha(' gefunden. Fehler beim Verarbeiten des Wertes für 'filter'. Deklaration ignoriert.

filter:Alpha(Opacity=35); /* For IE8 - See #6059 */

jquery-...5a09f84 (Zeile 929, Spalte 8)
'none', URL oder Filterfunktion erwartet, aber 'Alpha(' gefunden. Fehler beim Verarbeiten des Wertes für 'filter'. Deklaration ignoriert.

filter: Alpha(Opacity=30)/*{opacityFilterOverlay}*/;

jquery-...5a09f84 (Zeile 1177, Spalte 9)
'none', URL oder Filterfunktion erwartet, aber 'Alpha(' gefunden. Fehler beim Verarbeiten des Wertes für 'filter'. Deklaration ignoriert.

filter: Alpha(Opacity=30)/*{opacityFilterShadow}*/;

jquery-...5a09f84 (Zeile 1184, Spalte 9)
Unbekannte Eigenschaft 'line-break'. Deklaration ignoriert.

line-break: auto;

tooltip...5a09f84 (Zeile 14, Spalte 12)
'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden. Fehler beim Verarbeiten des Wertes für 'filter'. Deklaration ignoriert.

filter: alpha(opacity=0);

tooltip...5a09f84 (Zeile 27, Spalte 10)
'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden. Fehler beim Verarbeiten des Wertes für 'filter'. Deklaration ignoriert.

filter: alpha(opacity=90);

tooltip...5a09f84 (Zeile 31, Spalte 10)
Unbekannte Eigenschaft '-moz-border-radius'. Deklaration ignoriert.

-moz-border-radius: 3px;

direct_...5a09f84 (Zeile 83, Spalte 26)
Unbekannte Eigenschaft '-moz-filter'. Deklaration ignoriert.

-moz-filter: drop-shadow(0 0 5px rgba(150, 150, 150, 0.75));

direct_...5a09f84 (Zeile 92, Spalte 19)
Unbekannte Eigenschaft '-moz-border-radius'. Deklaration ignoriert.

-moz-border-radius: 0;

direct_...5a09f84 (Zeile 99, Spalte 26)
Unbekannte Eigenschaft '-moz-opacity'. Deklaration ignoriert.

-moz-opacity: 1;

direct_...5a09f84 (Zeile 155, Spalte 20)
'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden. Fehler beim Verarbeiten des Wertes für 'filter'. Deklaration ignoriert.

filter: progid: DXImageTransform.Microsoft.Alpha(opacity=100);

direct_...5a09f84 (Zeile 159, Spalte 16)
'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden. Fehler beim Verarbeiten des Wertes für 'filter'. Deklaration ignoriert.

filter: alpha(opacity=100);

direct_...5a09f84 (Zeile 160, Spalte 16)
Unbekannte Eigenschaft '-moz-opacity'. Deklaration ignoriert.

-moz-opacity: 0.80;

direct_...5a09f84 (Zeile 163, Spalte 20)
'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden. Fehler beim Verarbeiten des Wertes für 'filter'. Deklaration ignoriert.

filter: progid: DXImageTransform.Microsoft.Alpha(opacity=80);

direct_...5a09f84 (Zeile 167, Spalte 16)
'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden. Fehler beim Verarbeiten des Wertes für 'filter'. Deklaration ignoriert.

filter: alpha(opacity=80);

direct_...5a09f84 (Zeile 168, Spalte 16)
Unbekannte Eigenschaft 'user-select'. Deklaration ignoriert.

...ct:none;-ms-user-select:none;user-select:none;vertical-align:middle}.video-js .v...

style.c...5a09f84 (Zeile 75, Spalte 4494)
Unbekannte Pseudoklasse oder Pseudoelement '-webkit-full-screen'. Regelsatz wegen ungültigem Selektor ignoriert.

...portant;height:100%!important}.video-js:-webkit-full-screen{width:100%!important...

style.c...5a09f84 (Zeile 75, Spalte 4793)
Fehler beim Verarbeiten des Wertes für 'background'. Deklaration ignoriert.

background: -webkit-linear-gradient(top, rgba(76,76,76,0) 0%,rgba(19,19,19,0.5) ...

style.c...5a09f84 (Zeile 89, Spalte 13)
'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden. Fehler beim Verarbeiten des Wertes für 'filter'. Deklaration ignoriert.

filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#004c4c4c', e...

style.c...5a09f84 (Zeile 91, Spalte 9)
'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden. Fehler beim Verarbeiten des Wertes für 'filter'. Deklaration ignoriert.

filter: alpha(opacity=50);

version...5a09f84 (Zeile 18, Spalte 9)
'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden. Fehler beim Verarbeiten des Wertes für 'filter'. Deklaration ignoriert.

filter: alpha(opacity=100);

version...5a09f84 (Zeile 30, Spalte 9)
'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden. Fehler beim Verarbeiten des Wertes für 'filter'. Deklaration ignoriert.

filter: alpha(opacity=65);

firstru...5a09f84 (Zeile 25, Spalte 9)
Fehler beim Verarbeiten des Wertes für 'margin'. Deklaration ignoriert.

#cboxTitle{margin:8;}

colorbo...5a09f84 (Zeile 10, Spalte 18)
Unbekannte Eigenschaft 'zoom'. Deklaration ignoriert.

zoom: 1;

select2...5a09f84 (Zeile 9, Spalte 8)
Deklaration erwartet, aber '*' gefunden. Übersprungen bis zur nächsten Deklaration

*display: inline;

select2...5a09f84 (Zeile 10, Spalte 4)
Unbekannte Eigenschaft 'user-select'. Deklaration ignoriert.

user-select: none;

select2...5a09f84 (Zeile 49, Spalte 25)
Fehler beim Verarbeiten des Wertes für 'background-image'. Deklaration ignoriert.

background-image: -webkit-gradient(linear, left bottom, left top, color-stop(0, ...

select2...5a09f84 (Zeile 52, Spalte 22)
Fehler beim Verarbeiten des Wertes für 'background-image'. Deklaration ignoriert.

background-image: -webkit-linear-gradient(center bottom, #eee 0%, #fff 50%);

select2...5a09f84 (Zeile 53, Spalte 22)
'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden. Fehler beim Verarbeiten des Wertes für 'filter'. Deklaration ignoriert.

filter: progid:DXImageTransform.Microsoft.gradient(startColorstr = '#ffffff', en...

select2...5a09f84 (Zeile 55, Spalte 12)
Fehler beim Verarbeiten des Wertes für 'background-image'. Deklaration ignoriert.

background-image: -webkit-gradient(linear, left bottom, left top, color-stop(0, ...

select2...5a09f84 (Zeile 64, Spalte 22)
Fehler beim Verarbeiten des Wertes für 'background-image'. Deklaration ignoriert.

background-image: -webkit-linear-gradient(center bottom, #eee 0%, #fff 90%);

select2...5a09f84 (Zeile 65, Spalte 22)
'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden. Fehler beim Verarbeiten des Wertes für 'filter'. Deklaration ignoriert.

filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffffff', endC...

select2...5a09f84 (Zeile 67, Spalte 12)
'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden. Fehler beim Verarbeiten des Wertes für 'filter'. Deklaration ignoriert.

filter: alpha(opacity=0);

select2...5a09f84 (Zeile 128, Spalte 12)
Fehler beim Verarbeiten des Wertes für 'background-image'. Deklaration ignoriert.

background-image: -webkit-gradient(linear, left bottom, left top, color-stop(0, ...

select2...5a09f84 (Zeile 192, Spalte 22)
Fehler beim Verarbeiten des Wertes für 'background-image'. Deklaration ignoriert.

background-image: -webkit-linear-gradient(center bottom, #ccc 0%, #eee 60%);

select2...5a09f84 (Zeile 193, Spalte 22)
'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden. Fehler beim Verarbeiten des Wertes für 'filter'. Deklaration ignoriert.

filter: progid:DXImageTransform.Microsoft.gradient(startColorstr = '#eeeeee', en...

select2...5a09f84 (Zeile 195, Spalte 12)
Fehler beim Verarbeiten des Wertes für 'background'. Deklaration ignoriert.

...select2.png') no-repeat 100% -22px, -webkit-gradient(linear, left bottom, left t...

select2...5a09f84 (Zeile 238, Spalte 57)
Fehler beim Verarbeiten des Wertes für 'background'. Deklaration ignoriert.

...select2.png') no-repeat 100% -22px, -webkit-linear-gradient(center bottom, #fff ...

select2...5a09f84 (Zeile 239, Spalte 57)
Fehler beim Verarbeiten des Wertes für 'background'. Deklaration ignoriert.

...lect2-spinner.gif') no-repeat 100%, -webkit-gradient(linear, left bottom, left t...

select2...5a09f84 (Zeile 250, Spalte 59)
Fehler beim Verarbeiten des Wertes für 'background'. Deklaration ignoriert.

...lect2-spinner.gif') no-repeat 100%, -webkit-linear-gradient(center bottom, #fff ...

select2...5a09f84 (Zeile 251, Spalte 59)
Fehler beim Verarbeiten des Wertes für 'background-image'. Deklaration ignoriert.

background-image: -webkit-gradient(linear, left bottom, left top, color-stop(0, ...

select2...5a09f84 (Zeile 274, Spalte 22)
Fehler beim Verarbeiten des Wertes für 'background-image'. Deklaration ignoriert.

background-image: -webkit-linear-gradient(center bottom, #fff 0%, #eee 50%);

select2...5a09f84 (Zeile 275, Spalte 22)
'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden. Fehler beim Verarbeiten des Wertes für 'filter'. Deklaration ignoriert.

filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#eeeeee', endC...

select2...5a09f84 (Zeile 277, Spalte 12)
Fehler beim Verarbeiten des Wertes für 'background-image'. Deklaration ignoriert.

background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0, ...

select2...5a09f84 (Zeile 286, Spalte 22)
Fehler beim Verarbeiten des Wertes für 'background-image'. Deklaration ignoriert.

background-image: -webkit-linear-gradient(center top, #fff 0%, #eee 50%);

select2...5a09f84 (Zeile 287, Spalte 22)
'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden. Fehler beim Verarbeiten des Wertes für 'filter'. Deklaration ignoriert.

filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#eeeeee', endC...

select2...5a09f84 (Zeile 289, Spalte 12)
Unbekannte Eigenschaft 'user-select'. Deklaration ignoriert.

user-select: none;

select2...5a09f84 (Zeile 350, Spalte 25)
Fehler beim Verarbeiten des Wertes für 'background-image'. Deklaration ignoriert.

background-image: -webkit-gradient(linear, 0% 0%, 0% 100%, color-stop(1%, #eee),...

select2...5a09f84 (Zeile 451, Spalte 22)
Fehler beim Verarbeiten des Wertes für 'background-image'. Deklaration ignoriert.

background-image: -webkit-linear-gradient(top, #eee 1%, #fff 15%);

select2...5a09f84 (Zeile 452, Spalte 22)
Unbekannte Eigenschaft 'user-select'. Deklaration ignoriert.

user-select: none;

select2...5a09f84 (Zeile 529, Spalte 25)
'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden. Fehler beim Verarbeiten des Wertes für 'filter'. Deklaration ignoriert.

filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#eeeeee', endC...

select2...5a09f84 (Zeile 532, Spalte 12)
Fehler beim Verarbeiten des Wertes für 'background-image'. Deklaration ignoriert.

background-image: -webkit-gradient(linear, 0% 0%, 0% 100%, color-stop(20%, #f4f4...

select2...5a09f84 (Zeile 533, Spalte 22)
Fehler beim Verarbeiten des Wertes für 'background-image'. Deklaration ignoriert.

background-image: -webkit-linear-gradient(top, #f4f4f4 20%, #f0f0f0 50%, #e8e8e8...

select2...5a09f84 (Zeile 534, Spalte 22)
Name einer Medienfunktion erwartet, aber '-webkit-min-device-pixel-ratio' gefunden.

@media only screen and (-webkit-min-device-pixel-ratio: 1.5), only screen and (m...

select2...5a09f84 (Zeile 633, Spalte 24)
Unbekannte Pseudoklasse oder Pseudoelement '-webkit-input-placeholder'. Regelsatz wegen ungültigem Selektor ignoriert.

.contactdetails__header .contactdetails__name::-webkit-input-placeholder,

style.c...5a09f84 (Zeile 49, Spalte 47)
Unbekannte Pseudoklasse oder Pseudoelement '-ms-input-placeholder'. Regelsatz wegen ungültigem Selektor ignoriert.

.contactdetails__header .contactdetails__name:-ms-input-placeholder,

style.c...5a09f84 (Zeile 61, Spalte 46)
Unbekannte Pseudoklasse oder Pseudoelement 'placeholder-shown'. Regelsatz wegen ungültigem Selektor ignoriert.

.contactdetails__header .contactdetails__name:placeholder-shown,

style.c...5a09f84 (Zeile 67, Spalte 46)
Unbekannte Eigenschaft 'background-position-x'. Deklaration ignoriert.

background-position-x: 80px;

style.c...5a09f84 (Zeile 328, Spalte 22)
4
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src http://xxxxxxxx.xx 'unsafe-eval'").

onsubmit attribute on DIV element

GET http://xxxxxxxx.xx/xxxx/core/img/breadcrumb.svg
200 OK
        5msjquery....5a09f84 (Zeile 6)
GET http://xxxxxxxx.xx/xxxx/ocs/v2...s/notifications/api/v1/notifications?format=json
200 OK
        173msjquery....5a09f84 (Zeile 6)
GET http://xxxxxxxx.xx/xxxx/remote.php/dav/addressbooks
200 OK
        85msdav.js?...5a09f84 (Zeile 3640)
GET http://xxxxxxxx.xx/xxxx/apps/contacts/templates/groupList.html
200 OK
        6msangular...5a09f84 (Zeile 11442)
GET http://xxxxxxxx.xx/xxxx/apps/contacts/templates/addressBookList.html
200 OK
        5msangular...5a09f84 (Zeile 11442)
GET http://xxxxxxxx.xx/xxxx/apps/contacts/templates/contactImport.html
200 OK
        5msangular...5a09f84 (Zeile 11442)
GET http://xxxxxxxx.xx/xxxx/apps/contacts/templates/contactList.html
200 OK
        5msangular...5a09f84 (Zeile 11442)
GET http://xxxxxxxx.xx/xxxx/apps/contacts/templates/contactDetails.html
200 OK
        5msangular...5a09f84 (Zeile 11442)
GET http://xxxxxxxx.xx/xxxx/apps/contacts/templates/group.html
200 OK
        4msangular...5a09f84 (Zeile 11442)
PROPFIND http://xxxxxxxx.xx/xxxx/remote.php/dav/addressbooks
207 Multi-Status
        88msdav.js?...5a09f84 (Zeile 3640)
PROPFIND http://xxxxxxxx.xx/xxxx/remote.../dav/principals/users/michel.ketterle@sp-wil.ch/
207 Multi-Status
        68msdav.js?...5a09f84 (Zeile 3640)
PROPFIND http://xxxxxxxx.xx/xxxx/remote...av/addressbooks/users/michel.ketterle@sp-wil.ch/
207 Multi-Status
        101msdav.js?...5a09f84 (Zeile 3640)
PROPFIND http://xxxxxxxx.xx/xxxx/remote...ssbooks/users/michel.ketterle@sp-wil.ch/default/
207 Multi-Status
        191msdav.js?...5a09f84 (Zeile 3640)
PROPFIND http://xxxxxxxx.xx/xxxx/remote...ichel.ketterle@sp-wil.ch/SP-Wil_shared_by_cloud/
207 Multi-Status
        97msdav.js?...5a09f84 (Zeile 3640)
PROPFIND http://xxxxxxxx.xx/xxxx/remote...ichel.ketterle@sp-wil.ch/Presse_shared_by_cloud/
207 Multi-Status
        143msdav.js?...5a09f84 (Zeile 3640)
PROPFIND http://xxxxxxxx.xx/xxxx/remote...el.ketterle@sp-wil.ch/SP-Aktive_shared_by_cloud/
207 Multi-Status
        1.07sdav.js?...5a09f84 (Zeile 3640)
PROPFIND http://xxxxxxxx.xx/xxxx/remote...rs/michel.ketterle@sp-wil.ch/SP_shared_by_cloud/
207 Multi-Status
        1.12sdav.js?...5a09f84 (Zeile 3640)
PROPFIND http://xxxxxxxx.xx/xxxx/remote...hel.ketterle@sp-wil.ch/Adressen_shared_by_cloud/
207 Multi-Status
        1.16sdav.js?...5a09f84 (Zeile 3640)
PROPFIND http://xxxxxxxx.xx/xxxx/remote...av/addressbooks/users/michel.ketterle@sp-wil.ch/
207 Multi-Status
        66msdav.js?...5a09f84 (Zeile 3640)
REPORT http://xxxxxxxx.xx/xxxx/remote...ssbooks/users/michel.ketterle@sp-wil.ch/default/
207 Multi-Status
        127msdav.js?...5a09f84 (Zeile 3640)
PROPFIND http://xxxxxxxx.xx/xxxx/remote...av/addressbooks/users/michel.ketterle@sp-wil.ch/
207 Multi-Status
        155msdav.js?...5a09f84 (Zeile 3640)
REPORT http://xxxxxxxx.xx/xxxx/remote...ichel.ketterle@sp-wil.ch/SP-Wil_shared_by_cloud/
207 Multi-Status
        1.14sdav.js?...5a09f84 (Zeile 3640)
PROPFIND http://xxxxxxxx.xx/xxxx/remote...av/addressbooks/users/michel.ketterle@sp-wil.ch/
207 Multi-Status
        1.12sdav.js?...5a09f84 (Zeile 3640)
REPORT http://xxxxxxxx.xx/xxxx/remote...ichel.ketterle@sp-wil.ch/Presse_shared_by_cloud/
207 Multi-Status
        1.17sdav.js?...5a09f84 (Zeile 3640)
PROPFIND http://xxxxxxxx.xx/xxxx/remote...av/addressbooks/users/michel.ketterle@sp-wil.ch/
207 Multi-Status
        1.39sdav.js?...5a09f84 (Zeile 3640)
REPORT http://xxxxxxxx.xx/xxxx/remote...el.ketterle@sp-wil.ch/SP-Aktive_shared_by_cloud/
207 Multi-Status
        1.6sdav.js?...5a09f84 (Zeile 3640)
PROPFIND http://xxxxxxxx.xx/xxxx/remote...av/addressbooks/users/michel.ketterle@sp-wil.ch/
207 Multi-Status
        2.02sdav.js?...5a09f84 (Zeile 3640)
REPORT http://xxxxxxxx.xx/xxxx/remote...rs/michel.ketterle@sp-wil.ch/SP_shared_by_cloud/
207 Multi-Status
        1.81sdav.js?...5a09f84 (Zeile 3640)
PROPFIND http://xxxxxxxx.xx/xxxx/remote...av/addressbooks/users/michel.ketterle@sp-wil.ch/
207 Multi-Status
        111msdav.js?...5a09f84 (Zeile 3640)
REPORT http://xxxxxxxx.xx/xxxx/remote...hel.ketterle@sp-wil.ch/Adressen_shared_by_cloud/
207 Multi-Status
        2.15sdav.js?...5a09f84 (Zeile 3640)
GET http://xxxxxxxx.xx/xxxx/apps/contacts/templates/addressBook.html
200 OK
        2msangular...5a09f84 (Zeile 11442)
Fehler beim Verarbeiten des Wertes für 'top'. Deklaration ignoriert.

px

Fehler beim Verarbeiten des Wertes für 'left'. Deklaration ignoriert.

px

Fehler beim Verarbeiten des Wertes für 'top'. Deklaration ignoriert.

px

Fehler beim Verarbeiten des Wertes für 'left'. Deklaration ignoriert.

px

Fehler beim Verarbeiten des Wertes für 'top'. Deklaration ignoriert.

px

Fehler beim Verarbeiten des Wertes für 'left'. Deklaration ignoriert.

px

Fehler beim Verarbeiten des Wertes für 'top'. Deklaration ignoriert.

px

Fehler beim Verarbeiten des Wertes für 'left'. Deklaration ignoriert.

px

Fehler beim Verarbeiten des Wertes für 'top'. Deklaration ignoriert.

px

Fehler beim Verarbeiten des Wertes für 'left'. Deklaration ignoriert.

px

Fehler beim Verarbeiten des Wertes für 'top'. Deklaration ignoriert.

px

Fehler beim Verarbeiten des Wertes für 'left'. Deklaration ignoriert.

px
```

**Comment by aspdye** [comment] 2016-05-12 17:37
Adding, changing or removing Avatars in the contacts dringend is currently not implented. Such an function will come with the next version :wink:

**Comment by Mannshoch** [comment] 2016-05-12 17:59
Is the Old contact app also working with OC9.0.2? I need this to create a new list and share it.

Please add this info into:
https://apps.owncloud.com/content/show.php?content=168708

**Comment by Mannshoch** [comment] 2016-05-12 18:05
Will I be able to Link the Avatar from the Owncloud Users with the Avatar in my Adressbook if the User eMail address exist in my addressbock?

**Comment by aspdye** [comment] 2016-05-12 18:14
The old contacts app does not work with ownCloud 9.
You can add Profile Pictures with other CalDAV Clients (Android, iOS, ...) :wink:

**Comment by skjnldsv** [comment] 2016-05-14 09:19
duplicate of #344, #364.
see #380.

**Closed as completed by skjnldsv** 2016-05-14 09:19 UTC
