### ISSUE TITLE
Verify the OCS ID

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/contacts#892] opened 2015-05-07 09:35 UTC
The current entry of the ocsid is `166044` in all branches:
https://github.com/owncloud/contacts/blob/master/appinfo/info.xml#L20
https://github.com/owncloud/contacts/blob/stable8/appinfo/info.xml#L17
https://github.com/owncloud/contacts/blob/stable7/appinfo/info.xml#L16

However that app is only for oC 7: https://apps.owncloud.com/content/show.php?content=166044
oC 8.0 (and later**?**) should use `168708`: https://apps.owncloud.com/content/show.php?content=168708

This causes problems, when people try to enable the app from the recommended section rather then the disabled section: https://github.com/owncloud/core/issues/16092

Manually changing the ocsid resolves the issue.

**Comment by binarykitchen** [comment] 2015-05-07 11:03
the problem is still here, i cannot enable the contacts app, error `"App directory already exists"` still appears

**Comment by binarykitchen** [comment] 2015-05-27 21:20
Any news on this one? I am still seeing the error and have this log line

```
Fatal   remote  App not installed: contacts 2015-05-26T20:20:51+00:00
```

Weird.

**Comment by binarykitchen** [comment] 2015-05-28 21:58
Okay, here I am again and bugging (sorry): are there any news on this one bug?

**Comment by binarykitchen** [comment] 2015-06-07 00:34
It is still happening ...

**Comment by RealRancor** [comment] 2015-06-07 08:52
... which should be obvious as this issue is not closed as "fixed".

**Comment by binarykitchen** [comment] 2015-06-07 10:47
Yes. Just wanted to emphasize that it's still happening with v8.0.4 and there wasn't a comment for more than 10 days ...

**Comment by RealRancor** [comment] 2015-06-07 10:56
AFAIK there is no maintainer for the contacts app so you need to have some patience until some one have a look at this.

**Comment by DeepDiver1975** [comment] 2015-07-08 12:35
on the appstore we have 8.0 and 8.1 version of the app - both with ocsid 168708.

**Closed by DeepDiver1975** 2015-07-08 12:35 UTC
Labels: bug, regression

**Comment by binarykitchen** [comment] 2015-07-09 23:57
@DeepDiver1975 I still cannot enable the contact app on v8.1 - still says "App directory already exists"

**Comment by binarykitchen** [comment] 2015-07-09 23:58
Same problem happens with the Calendar v0.7.1

**Comment by RealRancor** [comment] 2015-07-10 04:50
@binarykitchen Remove those folders from your /apps folder. If you have old versions of the app in there you will always get this message.

**Comment by binarykitchen** [comment] 2015-07-10 07:33
Okay, I manually deleted these folders. Then I re-enabled the calendar, ran `sudo -u www-data php occ upgrade -vvv` and all seems to be fine. But when I go to the apps tab at `/index.php/settings/apps`, it tells me that the Calendar is enabled (I see a disabled button) but when I go to the Productivity tab, it tells me that the Calendar is disabled (I see an enabled button). Weird huh?

**Comment by DeepDiver1975** [comment] 2015-07-10 09:25
> But when I go to the apps tab at /index.php/settings/apps, it tells me that the Calendar is enabled (I see a disabled button) but when I go to the Productivity tab, it tells me that the Calendar is disabled (I see an enabled button). Weird huh?

This is the general confusion about the apps management page - we need to work on this.

Enabled and disabled categories reflect all apps which are installed in the instance.
Any other categories come from the app store and show apps which are available for installation.
