### ISSUE TITLE
Contacts-App crashing (>1500 contacts)

### ISSUE THREAD

**Issue by cova-it** [owncloud/contacts#869] opened 2015-03-28 21:12 UTC
After importing my contacts the contacts app has many problems to view all my contacts. Also my browser has some problems to display the list.

It would be great if contacts would get a paging feature.

**Comment by hope55** [comment] 2015-04-06 21:35
Same here. I've got 972 contacts, I get unresponsive script warning 2-3 times when I refresh the Contacts page.

**Comment by biolumin** [comment] 2015-05-13 05:46
+1

**Comment by fwolfst** [comment] 2015-05-26 09:27
+1 here, the "import" via SoGo-Connector with lots of contacts seems to work though. A thunderbird showed weird display issues, but at the end it looks as if all contacts were present in the adress book.

**Comment by RealRancor** [comment] 2015-06-15 13:16
Refs: https://github.com/owncloud/contacts/pull/337
https://github.com/owncloud/contacts/issues/334
https://github.com/owncloud/contacts/issues/869
https://github.com/owncloud/contacts/issues/576

At least https://github.com/owncloud/contacts/issues/576 is still open.

**Comment by jancborchardt** [comment] 2015-07-02 11:19
Closing as duplicate of https://github.com/owncloud/contacts/issues/582 which has more info on the topic. It’s set to 8.2 since we need a paging feature for this. Thanks and let’s continue over there! :)

**Closed by jancborchardt** 2015-07-02 11:19 UTC
