### ISSUE TITLE
Contacts in ownCloud 7.0.4 does not import phone numbers from Gmail CSV

### ISSUE THREAD

**Issue by Pastafarianist** [owncloud/contacts#827] opened 2015-02-16 19:23 UTC
I am running ownCloud 7.0.4 and I am having problems importing my contacts from Gmail. Here are the exact contents of the file I'm importing:

    Name,Given Name,Additional Name,Family Name,Yomi Name,Given Name Yomi,Additional Name Yomi,Family Name Yomi,Name Prefix,Name Suffix,Initials,Nickname,Short Name,Maiden Name,Birthday,Gender,Location,Billing Information,Directory Server,Mileage,Occupation,Hobby,Sensitivity,Priority,Subject,Notes,Group Membership,E-mail 1 - Type,E-mail 1 - Value,E-mail 2 - Type,E-mail 2 - Value,E-mail 3 - Type,E-mail 3 - Value,Phone 1 - Type,Phone 1 - Value,Phone 2 - Type,Phone 2 - Value,Phone 3 - Type,Phone 3 - Value,Phone 4 - Type,Phone 4 - Value,Phone 5 - Type,Phone 5 - Value,Website 1 - Type,Website 1 - Value
    Имя Фамилия,Имя,,Фамилия,,,,,,,,,,,,,,,,,,,,,,,* My Contacts ::: University ::: School,* ,email@example.com,,,,,Mobile,+7 000 000-00-00,,,,,,,,,,

I've stripped down the original file from Google, but the problem arises with the original file as well. Here's what I see after importing:

![](http://i.imgur.com/nkotpRk.png)

The phone number is not imported. Am I doing something wrong?

**Comment by babelouest** [comment] 2015-03-02 14:46
That's a duplicate of #818, a patch is coming for imports. I'm closing this bug but you can comment the original one if you want.

**Closed by babelouest** 2015-03-02 14:46 UTC
