### ISSUE TITLE
Losing contacts upon successful synchronization to phone

### ISSUE THREAD

**Issue by pejakm** [owncloud/contacts#979] opened 2015-07-10 19:34 UTC
I'm using DAVdroid to synchronize contacts from ownCloud to my phone. Two days ago I've upgraded ownCloud from 8.0.4 to 8.1.0 (Arch Linux packages). Everything went well, no problems with DAVdroid. But today I had to clear DAVdroid account on my phone and create it again. This is when problems started to appear: as soon as synchronization would finish (I watch progress using Contacts app), only 37 contacts would be displayed, out of ~470. No matter what I try, result is always the same, and the same 37 contacts are left in the end. I do not know what is the difference between those contacts who would remain and others. Logcat doesn't say anything useful. Tried latest and previous DAVdroid versions (0.8.0 and 0.8.1), the same result. Just now I reverted ownCloud to v8.0.4, and everything went normal.  DAVdroid's vCard version (in an account's settings) is 3.0, while it was 4.0 with my ownCloud v8.1.0. My conclusion is that ownCloud is the source of problems (therefore this issue report).
I have also uninstalled other apps which might tamper with contacts synchronization (Viber, WhatsApp).

### Server configuration
**Operating system**:
Arch Linux
**Web server:**
nginx-1.8.0
**Database:**
sqlite-3.8.10.2
**PHP version:**
5.6.10
**ownCloud version:**
8.1.0
**Updated from an older ownCloud or fresh install:**
from 8.0.4
**External storage, Encryption, External User-Backend**
NO
**The content of config/config.php:**
haven't changed it manually

**Comment by agru** [comment] 2015-07-13 08:47
I have the same problem - but in my case nearly all contacts are missing on my Android phone and on my Android tablet. Big problem for me! Syncing with newest version of DAVdroid works without any error message ... but nearly all contacts are gone. Only the absolute newest ones are synced, although I deleted the DAVdroid-account on the phone and tried to sync back all contacts. So - all contacts are new for the phone ... but they are not imported.
Any help?

**Comment by gvde** [comment] 2015-07-13 09:20
Are only shared address books affected? I had problems with address books which are shared by others. They wouldn't sync to OSX or iOS... See #982

**Comment by agru** [comment] 2015-07-13 09:49
As far as I can see this thread is related to Android phones and tablets. Can't say anything for OS X or iOS.

For Android I just switched from DAVdroid to 'CardDAV Sync free' and now my Contacts are synced. So it looks as if this is a problem with DAVdroid only

**Comment by privong** [comment] 2015-07-20 03:01
To close the loop on this, the consensus from the discussion on [bitfireAT/davdroid/#578](https://github.com/bitfireAT/davdroid/issues/578) is that this is an owncloud issue, arising from #581.

**Comment by phsc** [comment] 2015-07-20 07:38
This issue is one more reason, why @DeepDiver1975's proposal is a great idea:
http://owncloud.10557.n7.nabble.com/Separation-of-frontend-and-backend-td15412.html

**Comment by rfc2822** [comment] 2015-07-20 10:53
Can be closed as a duplicate of #581, I guess.

**Comment by frankstanek** [comment] 2015-09-13 20:04
Same problem. Only 13 out of 28 contacts are synced from ownCloud to Android using DAVdroid. Used to work before upgrading to ownCloud 8.1. Using DAVdroid 0.8.4.1.

Server configuration:
Operating system:
Debian 7.9
Web server:
Apache 2.2.22-13+deb7u6
Database:
MySQL 5.5.44-0+deb7u1
PHP version:
5.4.44-0+deb7u1
ownCloud version:
8.1.1-1
Updated from an older ownCloud or fresh install:
Multiple updates over time, from 7.x
External storage, Encryption, External User-Backend
No
The content of config/config.php:
No manual change

**Comment by pejakm** [comment] 2015-09-22 16:06
@frankstanek It should be fixed via https://github.com/owncloud/contacts/commit/484fce0941e367cb984298bc4bc7a74f1505a5aa

**Closed** 2015-09-22 16:06 UTC
