### ISSUE TITLE
Undefined index: addressBookId at /var/www/owncloud/apps/contacts/lib/hooks.php#109

### ISSUE THREAD

**Issue by tomcatcw** [owncloud/contacts#1127] opened 2016-01-15 14:42 UTC
Hi,

I updated owncloud to 8.2.2.2 on a Debian Server. When I want to create a new contact, owncloud does not save it. When I reload the contact page I only see an entry with "#" and nothing in it.

On admin page there was created a error entry named: Undefined index: addressBookId at /var/www/owncloud/apps/contacts/lib/hooks.php#109 

Does someone noticed the issue?

Greetings

**Comment by DeepDiver1975** [comment] 2016-01-15 14:49
please reopen in https://github.com/owncloud/contacts - THX

**Comment by DeepDiver1975** [comment] 2016-01-15 14:50
sorry for closing :see_no_evil:

**Comment by tomcatcw** [comment] 2016-01-15 14:59
In addition the following hint: I imported my entire contacts via *.vcf. When I edit contacts via iPhone, the changes are saved. However when I edit via owncloud website the changed are not saved and I get the above mentioned error entry.

**Comment by gvde** [comment] 2016-01-15 15:15
Please use the template from the contribution guidelines...

**Comment by tomcatcw** [comment] 2016-01-15 15:25
Sorry to this. Where can I find that template?

**Comment by RealRancor** [comment] 2016-01-17 12:17
@tomcatcw When creating a new issue you're asked in a yellow box: "Please review the guidelines for contributing to this repository.". This link points to:

https://github.com/owncloud/contacts/blob/master/CONTRIBUTING.md#short-version

where you can find the issue template.

**Comment by RealRancor** [comment] 2016-01-17 12:18
The message itself looks similar to https://github.com/owncloud/contacts/issues/1121 where also no one has provided the needed infos yet.

**Comment by Georg-Git** [comment] 2016-01-26 21:44
### Steps to reproduce
Insert new contact in android
sync via DAVDroid to OC

### Expected behaviour
sync to OC without error

### Actual behaviour
New contact is synced from android to OC

But OC Log Error:
Undefined index: addressBookId at .../apps/contacts/lib/hooks.php#109

### Server configuration
Linux gentoo x86_64
Apache
MariaDB Version: 10.0.22
PHP Version 5.5.31 FPM/FastCGI

ownCloud 8.2.2 (stable) fresh install

**List of activated apps:**
Activity  2.1.3
Deleted files  0.7.0
First Run Wizard  1.1
Gallery  14.2.0
Mail Template Editor  0.1
PDF Viewer  0.7
Share Files  0.7.0
Text Editor  2.0
Updater  0.6
Versions  1.1.0
Video Viewer  0.1.3
Calendar  0.8.1
Contacts  0.5.0.0 stable 8.2 branch 2016-01-17


**The content of config/config.php:**
```
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'trusted_domains' =>
  array (0 => 'xxx',),
  'overwritewebroot' => '/xxx',
  'overwrite.cli.url' => 'https://xxx',
  'datadirectory' => '/xxx',
  'dbtype' => 'mysql',
  'version' => '8.2.2.2',
  'dbname' => 'xxx',
  'dbhost' => 'xxx',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'installed' => true,
  'mail_smtpmode' => 'sendmail',
  'mail_from_address' => 'xxx',
  'mail_domain' => 'xxx',
  'loglevel' => 1,
  'DEBUG' => '0',
  'theme' => '',
  'maintenance' => false,
  'secret' => 'xxx',
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'logtimezone' => 'Europe/Berlin',
  'trashbin_retention_obligation' => 'auto',
```

No ext storage, no excryption, no ext user


#### ownCloud log (data/owncloud.log)
```
{"reqId":"VqfUicLVBcwAACSdCWoAAABH","remoteAddr":"xxx","app":"PHP","message":"Array to string conversion at \/xxx\/lib\/private\/template\/functions.php#36","level":3,"time":"2016-01-26T21:18:19+01:00"}
{"reqId":"VqfVHsLVBcwAACSdC2cAAABp","remoteAddr":"xxx","app":"PHP","message":"Undefined index: addressBookId at \/xxx\/apps\/contacts\/lib\/hooks.php#109","level":3,"time":"2016-01-26T21:20:48+01:00"}
{"reqId":"VqfXfMLVBcwAACsNCOUAAAA6","remoteAddr":"xxx","app":"PHP","message":"Array to string conversion at \/xxx\/lib\/private\/template\/functions.php#36","level":3,"time":"2016-01-26T21:30:52+01:00"}
```

#### oc_contacts_cards:
```
BEGIN:VCARD
VERSION:4.0
UID:70816e66-442d-4a18-a8f2-f28943bf3b9f
PRODID:-//ownCloud//NONSGML Contacts 0.5.0.0//EN
FN:Aaa Atest
N:Atest;Aaa;;;
TEL;TYPE=cell:01234567
REV:2016-01-26T20:20:48+00:00
END:VCARD
```

**Comment by gvde** [comment] 2016-01-27 05:12
You are missing the web server logs. You have three owncloud log messages covering 12 minutes. That is definitely not a single new contact synced into owncloud...

**Comment by Georg-Git** [comment] 2016-01-27 08:04
?
There is only one error message related to contact app:

1. OC Log Error .../functions.php#36
known core Bug when requesting the admin panel in a browser
https://github.com/owncloud/core/issues/17468

2. OC Log Index Error .../hooks.php#109
21:20:46 WebLog: PUT Message of DAVDroid with one new contact
21:20:48 OC Log: Index Error in /hooks.php#109
see web log attached.

3. OC Log Error functions.php#36
see above no 1


#### Apache Log
```
[26/Jan/2016:21:20:45 +0100] "PROPFIND /myklaut/remote.php/carddav/addressbooks/georg/georg.cloud/ HTTP/1.1" 207 816 "-" "DAVdroid/0.9.1.3 (2016/01/02; dav4android) Android/5.0.2" 979 5021
[26/Jan/2016:21:20:46 +0100] "PUT /myklaut/remote.php/carddav/addressbooks/georg/georg.cloud/70816e66-442d-4a18-a8f2-f28943bf3b9f.vcf HTTP/1.1" 201 - "-" "DAVdroid/0.9.1.3 (2016/01/02; dav4android) Android/5.0.2" 836 696
[26/Jan/2016:21:22:25 +0100] "POST /myklaut/index.php/settings/admin/log/level HTTP/1.1" 200 37 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36" 1397 1135
[26/Jan/2016:21:22:25 +0100] "GET /myklaut/index.php/settings/admin/log/entries?offset=0&count=13 HTTP/1.1" 200 1343 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36" 736 2397
```

**Comment by Georg-Git** [comment] 2016-01-27 08:40
Addendum:
I can reproduce OC Log Index Error in /hooks.php#109 also with adding a new contact directly in OC Contact App. So this error is not related to android or DAVDroid.

But different to the initial bugreport of tomcatcw I have no errors inside of my contact data: in OC contact app I could add a new contact, store it, edit it again and changes of data were stored in OC correctly.

In my case the anomalie is only the index error in OC Log.

**Comment by gvde** [comment] 2016-01-27 08:45
It's extremely helpful if people posted only related log messages and not completely unrelated ones... It makes things so much easier...

Try PR #1134

**Comment by Georg-Git** [comment] 2016-01-27 12:56
@gvde: Yes - that is exactly my point of view!!

It could be so easy, because we are talking only about 0 and 1, only black and white - and we are talking here not about the grey shadowed real world.

I would like to reduce this complicated things even furthermore:
0 and 1 meaning false and true.

But I do not want to accept false any more!
Lets reduce this complicated world to the true state!

So I am telling all the testers here I will accept only bug reports with code texts included that will fix the reported bug.
That will be extremely helpful for the developer!

And for the developer I have to state I am willing to accept only code without any bugs!
That will be extremely helpful for the user! And so we do not need this stupid testers and bug reporters anymore.

;-))))

I was dreaming - and kidding ;-))


Coming back to the error report of tomcatcw.
1.) Error in OC log is fixed now.
2.) But he reported another issue I can reproduce and which is not related to the index error in OC log:

Add a new contact in OC contact app with the following property
(only cutout of the new vcard in oc_contacts_cards):
N:Test;DDD;;;
FN:DDD Test

In the contact app overview it is listed as
Test;DDD

After editing the name of the contact in the contact app the vcard property changed as follow:
N:Test;DDD;;;
FN:DDD Test1234

But only the FN is changed, the N property remains unchanged.
In the overwiew only the N Property is displayed - so the contact looks unchanged.

**Comment by gvde** [comment] 2016-01-27 13:22
That's a different issue and has nothing to do with the subject of this issue. Please open a new issue for that. And don't forget to try all open and closed pull requests regardings those semicolons or FN/N properties. There are still some open pull requests and some are merge but not yet released...

**Comment by Georg-Git** [comment] 2016-01-27 14:46
@tomcatcw: please take over.
I am not interested in any gui problems of the old contact app.

I am desperately waiting for the new contact app, coming in March 2016, hopefully ...
 ;-)

**Comment by Georg-Git** [comment] 2016-01-27 14:53
FN and N Problem is here:
https://github.com/owncloud/contacts/issues/1059

**Comment by sokai** [comment] 2016-01-29 10:31
FYI: I noticed that error message today, too. :-/

**Steps:**
* Created a new abook (GUI).
* Created a new contact with TB (38.5.1, SOGo Connector 31.0.2) produced the error message
```
{"reqId":"uTlawsDbJ\/ORGMH4rANX","remoteAddr":"XXX.XXX.XXX.XXX","app":"PHP","message":"Undefined index: addressBookId at \/$PATH\/apps\/contacts\/lib\/hooks.php#109","level":3,"time":"2016-01-29T10:18:18+00:00"}
```
* **But:** the new contact was created successfully.

**Info:**
Creating new contacts with GUI  and sync in TB also works without error message.
Error message appears if I **create** a new contact **or move** (from an other abook) contacts in/to the new abook. (Deleting a contact is fine withot a message …)

Here I give you the concerning Apache log:
```
XXX.XXX.XXX.XXX - - [29/Jan/2016:11:18:18 +0100] "PROPFIND /remote.php/carddav/addressbooks/$USER/$NEWABOOK/ HTTP/1.1" 207 2245 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Thunderbird/38.5.1 Lightning/4.0.5.2"
XXX.XXX.XXX.XXX - - [29/Jan/2016:11:18:18 +0100] "PUT /remote.php/carddav/addressbooks/$USER/$NEWABOOK/C6EF4111-ED20-0001-F0D3-B8A0117315B9.vcf HTTP/1.1" 201 805 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Thunderbird/38.5.1 Lightning/4.0.5.2"
XXX.XXX.XXX.XXX - - [29/Jan/2016:11:18:18 +0100] "PROPFIND /remote.php/carddav/addressbooks/$USER/$NEWABOOK/C6EF4111-ED20-0001-F0D3-B8A0117315B9.vcf HTTP/1.1" 207 1540 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Thunderbird/38.5.1 Lightning/4.0.5.2"
XXX.XXX.XXX.XXX - - [29/Jan/2016:11:18:19 +0100] "PROPFIND /remote.php/carddav/addressbooks/$USER/$NEWABOOK/ HTTP/1.1" 207 1524 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Thunderbird/38.5.1 Lightning/4.0.5.2"
```
Maybe this can help you a bit … :-)

**Comment by gvde** [comment] 2016-01-29 10:35
@sokai Apply the fix and it's gone...

**Comment by Georg-Git** [comment] 2016-01-29 11:01
And before applying the fix please download first this version of contact:
[https://github.com/owncloud/contacts/tree/stable8.2]

Due to the missing maintainer of this old contact app, the version number is not changed after the last merge, but the last merged PR is very important!

After loosing to much data of my contacts when syncing with sogo I change and want to recommend this new add in for thunderbird:
[https://addons.mozilla.org/de/thunderbird/addon/cardbook/]

**Comment by DeepDiver1975** [comment] 2016-02-01 15:28
prs fixing this have been merged

**Closed** 2016-02-01 15:27 UTC

**Comment by bcutter** [comment] 2016-05-10 18:47
Still existing in OC v8.2.4 with corresponding contacts app version (0.5.0.0)... did I miss something?

**Comment by RealRancor** [comment] 2016-05-10 20:00
@bcutter The old pre-oC9 is deprecated/unmaintained so this fix probably never was released. Just move on to oC9 and the new contacts app.
