### ISSUE TITLE
importing csv file to a seperate contact list

### ISSUE THREAD

**Issue by wgregori** [owncloud/contacts#469] opened 2016-07-27 22:29 UTC
I'm not sure if this should be in the core repo (it does deal with CardDav) but here goes... I'm using owncloud 9 and I understand that some functionality that we had in Contacts OC-8.2 versions will be added over time.  

My question is importing records into contacts.  

Previously we could direct a new import to a specific contact list.  No more.  I understand that this is a CardDav/Contacts service so I'm wondering when we might see this important feature return.

Thanks,
Wayne

**Comment by Henni** [comment] 2016-07-28 08:14
closing as duplicate of #414

**Closed as completed by Henni** 2016-07-28 08:14 UTC
