### ISSUE TITLE
enhancement show favourite icon on list view

### ISSUE THREAD

**Issue by libasys** [owncloud/contacts#959] opened 2015-07-02 13:54 UTC
it would be really awesome if the favourite icon shown in the listview, also!

**Comment by jancborchardt** [comment] 2015-07-08 09:47
Duplicate of https://github.com/owncloud/contacts/issues/344 :) Would be great if you can submit a pull request for this! :) (Although we will rework the app from tables to divs first: #946 )

**Closed by jancborchardt** 2015-07-08 09:47 UTC
