### ISSUE TITLE
Google CSV import fails to import more than one type of phone number per contact

### ISSUE THREAD

**Issue by gstuartj** [owncloud/contacts#817] opened 2015-02-10 20:54 UTC
Owncloud 8.0 (8.0.0-5 package, Ubuntu, fresh install)
PHP version: PHP 5.5.9-1ubuntu4.5
DB: MySQL Ver 14.14 Distrib 5.5.41

When importing a Google formatted CSV the Contacts app fails to properly populate all phone fields. Phone field still fails to populate after applying PR #816, which fixes the import of home phone numbers from Google CSVs.

**Edit:** This occurs when a contact has more than one type of phone number associated. Only phones of one type get imported. See my post below.

**Comment by babelouest** [comment] 2015-02-10 21:18
I can't reproduce this but with a gmail csv file I just exported:
```csv
Name,Given Name,Additional Name,Family Name,Yomi Name,Given Name Yomi,Additional Name Yomi,Family Name Yomi,Name Prefix,Name Suffix,Initials,Nickname,Short Name,Maiden Name,Birthday,Gender,Location,Billing Information,Directory Server,Mileage,Occupation,Hobby,Sensitivity,Priority,Subject,Notes,Group Membership,Phone 1 - Type,Phone 1 - Value
Owncloud 8 test,Owncloud,8,test,,,,,,,,,,,,,,,,,,,,,,,* My Contacts,Mobile,444 111 5552
```
Do you have other properties that may cause the problem ?

**Comment by gstuartj** [comment] 2015-02-10 21:39
It looks like the bug only occurs with the contact has phone numbers of more than one type associated. I created a contact with home, work, and mobile phone numbers, exported to CSV. The import only populated the home phone field and excluded the other two numbers.

**Resulting Mobile Phone field:** `18005556666 ::: 14555559999`
**CSV data:**
```
Name,Given Name,Additional Name,Family Name,Yomi Name,Given Name Yomi,Additional Name Yomi,Family Name Yomi,Name Prefix,Name Suffix,Initials,Nickname,Short Name,Maiden Name,Birthday,Gender,Location,Billing Information,Directory Server,Mileage,Occupation,Hobby,Sensitivity,Priority,Subject,Notes,Group Membership,Phone 1 - Type,Phone 1 - Value,Phone 2 - Type,Phone 2 - Value,Phone 3 - Type,Phone 3 - Value
Test Case,Test,,Case,,,,,,,,,,,,,,,,,,,,,,,* My Contacts,Home,18005556666,Mobile,14555559999,Work,18475553293
```

**Comment by babelouest** [comment] 2015-02-11 22:17
I have a patch ready, will provide it asap

**Comment by babelouest** [comment] 2015-02-25 19:23
There is an ongoing upgrade to sabre ( #826 ) which looks to make problems on imports: multiple values are separated by a comma `,`, but commas are escaped during the process, I'll retry when sabre upgrade will be completed to see if there are other issues.

**Comment by LEDfan** [comment] 2015-03-12 13:23
@babelouest any news on this?

**Comment by babelouest** [comment] 2015-03-12 13:29
@LEDfan , I'm waiting for the new sabre library to be integrated into contacts ( #826 ) before finalizing some import bugfixes

**Comment by babelouest** [comment] 2015-07-19 23:11
this is fixed now, I'm closing this issue

**Closed by babelouest** 2015-07-19 23:11 UTC
Labels: import
